### ISSUE TITLE
SQL & Remote databases support

### ISSUE THREAD

**Issue by GitHunter0** [markfairbanks/tidytable#124]
Is it possible to use `tidytable` together with `dbplyr` in order to support remote databases operations?

Thanks for the work, tidytable is a great package.

**Comment by GitHunter0** [comment]
Hey, thanks very much for the reply. I asked because it would convenient to use one syntax for all purposes but alternating with dplyr syntax is not that hard too. 
By the way, congratulations for tidytable package, It was much needed.

**Comment by markfairbanks** [comment]
> By the way, congratulations for tidytable package, It was much needed.

Thanks! Glad it's working out for you.

> I asked because it would be convenient to use one syntax for all purposes

Ahhh gotcha, I misunderstood. Currently there aren't any plans to extend the functionality to remote databases. One of the main reasons I built `tidytable` was that `dtplyr` was missing a lot of key functionality. `dbplyr`, on the other hand, seems to cover remote databases operations pretty well.
