### ISSUE TITLE
Console printing is inconsistent

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#139]
If the user only opens an R script the tidytable will print with `trunc_mat()` formatting.

If the user opens an Rmarkdown notebook and prints within the notebook it will print correctly - whether with paged printing or `trunc_mat()` formatting.

If the user opens an Rmarkdown notebook and `paged.print = TRUE` (or kept as the default `NULL`), console printing or printing from a normal R script now prints as a normal data.frame. Printing in console works correctly if `paged.print = FALSE`.

Related #137

**Comment by moutikabdessabour** [comment]
how about using `isTRUE(getOption('knitr.in.progress'))` to check whether the data.table is printed inside an Rmarkdown notebook as referenced here by [Yihui](https://github.com/yihui/knitr/issues/926).

**Comment by markfairbanks** [comment]
Using `isTRUE(getOption('knitr.in.progress'))` tracks if the printing is being done during knitting. However when doing normal coding it makes paged printing not occur. Try running this code in a new notebook and it prints without paged printing:

````r
```{r setup}
library(tibble)
```

```{r}
print.test_class <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
  if (knitr_installed && knitr_loaded) {

    if (isTRUE(getOption('knitr.in.progress')))
      print(rmarkdown::paged_table(x))
    else
      print_mat(x, n = n, width = width, n_extra = n_extra)

  } else {
    print_mat(x, n = n, width = width, n_extra = n_extra)
  }
}

print_mat <- function(x, n = NULL, width = NULL, n_extra = NULL) {
  mat <- trunc_mat(x, n = n, width = width, n_extra = n_extra)
  mat$summary <- unname(mat$summary)
  print(mat)
}

knitr_installed <- rlang::is_installed("knitr")
knitr_loaded <- "knitr" %in% loadedNamespaces()

test_df <- data.frame(x = 1:3)

class(test_df) <- c("test_class", "data.frame")

test_df
```
````

**Comment by markfairbanks** [comment]
One thing worth noting is that using `isTRUE(getOption('knitr.in.progress'))` alongside the current `knitr::opts_chunk$get()$paged.print %||% TRUE` will make the printing work correctly when knitting a document.

**Comment by moutikabdessabour** [comment]
this is the output of `print(rmarkdown::paged_table(test_df))`
![][https://i.imgur.com/bbAE0ct.png]

**Comment by markfairbanks** [comment]
Whoops, I had `knitr::opts_chunk$set(paged.print = FALSE)` in the setup chunk. I'll re-edit this comment https://github.com/markfairbanks/tidytable/issues/139#issuecomment-699544305. The `isTRUE(getOption('knitr.in.progress'))` option helps.

I just made the edit so knitting now prints correctly. See [here](https://github.com/markfairbanks/tidytable/blob/master/R/print.R).

So far the things I've tried from the thread you linked don't fix this overall issue we're talking about. Thanks for the help on all this (and thanks for catching the knit print issue)

**Comment by moutikabdessabour** [comment]
just to fully grasp the issue. should the output be an html table not as shown in my other comment, right?

**Comment by moutikabdessabour** [comment]
@markfairbanks should the condition be `paged_print && knitting`?

**Comment by moutikabdessabour** [comment]
Okay so after some testing I found that that this code gives the desired output ie an html table :
```

print.tidytable <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
  if (isTRUE(getOption('knitr.in.progress'))) {
    if (knitr::opts_chunk$get()$paged.print %||% TRUE)
      rmarkdown:::print.paged_df(x)
    else
      print_mat(x, n = n, width = width, n_extra = n_extra)
  } else {
    print_mat(x, n = n, width = width, n_extra = n_extra)
  }
}

print_mat <- function(x, n = NULL, width = NULL, n_extra = NULL) {
  mat <- trunc_mat(x, n = n, width = width, n_extra = n_extra)
  mat$summary <- unname(mat$summary)
  print(mat)
}

print.tidytable(data.table(mtcars))
tibble(mtcars)
```
![Screen Shot 2020-09-27 at 5 23 38 AM](https://user-images.githubusercontent.com/11250014/94364973-21ef2000-0082-11eb-8567-43df145bfac6.png)

**Comment by markfairbanks** [comment]
> just to fully grasp the issue. should the output be an html table not as shown in my other comment, right?

The goal is to have tidytables print like tibbles do.

There are 5 cases:

1. Printing in console (whether directly or from an R script)

<img width="284" alt="Screen Shot 2020-09-27 at 7 21 53 AM" src="https://user-images.githubusercontent.com/28766000/94367325-c711f480-0092-11eb-9987-279e650b8a34.png">

2. Printing in Rmarkdown - default settings

<img width="943" alt="Screen Shot 2020-09-27 at 7 28 14 AM" src="https://user-images.githubusercontent.com/28766000/94367373-22dc7d80-0093-11eb-8379-9b55b8d84bb4.png">

3. Printing in Rmarkdown - `paged.print = TRUE`

<img width="946" alt="Screen Shot 2020-09-27 at 7 34 18 AM" src="https://user-images.githubusercontent.com/28766000/94367526-24f30c00-0094-11eb-9018-d5c3d227d3f8.png">

4. Printing in Rmarkdown - `paged.print = FALSE`

<img width="943" alt="Screen Shot 2020-09-27 at 7 34 52 AM" src="https://user-images.githubusercontent.com/28766000/94367537-32a89180-0094-11eb-81cd-8bd62cb9e049.png">

5. Printing when knitting

<img width="336" alt="Screen Shot 2020-09-27 at 7 35 49 AM" src="https://user-images.githubusercontent.com/28766000/94367549-448a3480-0094-11eb-9242-a966cf7a1239.png">

2 & 3 use "paged printing".

1, 4, & 5 use tibble's special print.

**Comment by moutikabdessabour** [comment]
can you please explain the difference between knitting vs printing in Rmarkdown?

**Comment by markfairbanks** [comment]
* knitting - Running "knit" in Rmarkdown
* printing - Running the code normally

Open a new Rmarkdown notebook and replace with the code below. Then use the "Run All" option in RStudio.

<img width="889" alt="Screen Shot 2020-09-27 at 10 12 08 AM" src="https://user-images.githubusercontent.com/28766000/94371237-eff1b400-00a9-11eb-8e6a-3a8ad3d25c3c.png">


````r
---
title: "R Notebook"
---

```{r setup}
pacman::p_load(tidyverse)
```

```{r}
tibble(x = 1:20, y = 1:20)
```
````

**Comment by moutikabdessabour** [comment]
Okay I think I found a solution instead of calling `rmarkdown::paged_table` which does nothing but change the class of the argument to `c("df_paged", "data.frame")` why not implement it directly whilst keeping the old class i.e keeping `"data.table"` and this simple idea seems to resolve the issue as the print would try the `rmarkdown::print.df_paged` then backtrack to the next class `data.frame` if we called `rmarkdown::paged_table` and `data.table` if we do it like this 
```

print.tidytable <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
  if (knitr_installed && knitr_loaded) {

    paged_print <- knitr::opts_chunk$get()$paged.print %||% TRUE
    knitting <- isTRUE(getOption('knitr.in.progress'))
    
    if (paged_print && !knitting){
      class(x) <- c("paged_df", class(x))
      print(x)
    }else
      print_mat(x, n = n, width = width, n_extra = n_extra)

  } else {
    print_mat(x, n = n, width = width, n_extra = n_extra)
  }
}
```

**Comment by moutikabdessabour** [comment]
Also we need to add the line to force knitr to use our print:
``` r
knit_print.tidytable <- print.tidytable
```

**Comment by moutikabdessabour** [comment]
Ok so the code above achieves the same output as tibble:
1. Printing in console (whether directly or from an R script)
![Screen Shot 2020-09-27 at 12 06 39 PM](https://user-images.githubusercontent.com/11250014/94373385-13245f80-00ba-11eb-9759-2dab3dc9c68a.png)
2. Printing in Rmarkdown - default settings
![Screen Shot 2020-09-27 at 12 06 23 PM](https://user-images.githubusercontent.com/11250014/94373397-29cab680-00ba-11eb-9b62-4edb61725de8.png)
3. Printing in Rmarkdown - `paged.print = TRUE`
![Screen Shot 2020-09-27 at 12 06 09 PM](https://user-images.githubusercontent.com/11250014/94373401-2f280100-00ba-11eb-9f5d-006cec97b44c.png)
3. Printing in Rmarkdown - `paged.print = FALSE`
![Screen Shot 2020-09-27 at 12 05 39 PM](https://user-images.githubusercontent.com/11250014/94373429-5088ed00-00ba-11eb-8c3a-080a7d3e4863.png)
3. Printing when kniting
![Screen Shot 2020-09-27 at 12 10 20 PM](https://user-images.githubusercontent.com/11250014/94373441-6eeee880-00ba-11eb-924a-9e7ac058dd4a.png)

**Comment by markfairbanks** [comment]
This does look pretty good.

Though I found one more case where your current `print.tidytable` implementation seems to not work.

6. Printing in Rmarkdown - using current chunk options
Note that `paged.print = TRUE` in the setup chunk, but `paged.print = FALSE` in the chunk where the code is executed.

<img width="937" alt="Screen Shot 2020-09-27 at 12 31 08 PM" src="https://user-images.githubusercontent.com/28766000/94373908-72d03a00-00bd-11eb-9eca-ef0846439e35.png">

> Okay I think I found a solution instead of calling rmarkdown::paged_table which does nothing but change the class of the argument to c("paged_df", "data.frame")

But this is a really interesting point. Basically Rmarkdown is looking for `"paged_df"` in the class, then decides "do I use a paged print or do I pass it to the next class".

I was thinking - what if we changed the `print.R` file to this:

```r
#' @export
print.tidytable <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
  mat <- trunc_mat(x, n = n, width = width, n_extra = n_extra)
  mat$summary <- unname(mat$summary)
  print(mat)
}

#' @export
knit_print.tidytable <- print.tidytable

#' @export
vec_ptype_abbr.tidytable <- function(x) {
  "tidytable"
}
```

And then inside of the [as_tidytable.R](https://github.com/markfairbanks/tidytable/blob/master/R/as_tidytable.R) file there is a helper function called `add_class()`. What if we change that to this?

```r
add_class <- function(.df) {

  class(.df) <- c("paged_df", "tidytable", "data.table", "data.frame")

  .df

}
```

tidytables would always carry that extra class of `"paged_df"`, but printing seems to always work as intended.

Thoughts? Does that seem to work when you use it?

**Comment by moutikabdessabour** [comment]
I think that is a great solution it works seamlessly in all the cases. the only minor "issue" is that it prints the row numbers. I'm now sifting through `rmarkdown:::paged_table_html` code to find from where this "issue" is rising.

**Comment by moutikabdessabour** [comment]
this so called issue arises from `.row_names_info(tibble(mtcars),type=1)` being equal to `-32` and `.row_names_info(addclass(mtcars),type=1)` == `32`.
this comes from the first lines of `rmarkdown:::paged_table_html` that creates the html for the paged table (`rmarkdown:::print.paged_df` calls it)
```
addRowNames <- if (is.null(addRowNames)) 
        (.row_names_info(x, type = 1) > 0)
    else addRowNames
```
basically we can add an option to the `tidytable` constructor `keep.row.names=F` and then if true make the first column equal to the rownames (I guess this is the default behavior of tibble and data.table) 
```
attr(dt, "row.names") <- .set_row_names(nrow(dt))
```

**Comment by markfairbanks** [comment]
Do you have an example of where it's printing row numbers where tibble isn't? From what I've been printing it seems to print the same as tibble does.

**Comment by moutikabdessabour** [comment]
if you use `mtcars` to test the printing mechanism this 'issue' shows up
![Screen Shot 2020-09-27 at 1 57 03 PM](https://user-images.githubusercontent.com/11250014/94377233-93f05500-00d4-11eb-8c24-65372c37a14d.png)
![Screen Shot 2020-09-27 at 1 56 42 PM](https://user-images.githubusercontent.com/11250014/94377232-918dfb00-00d4-11eb-8dd9-b95b6c75ed34.png)

**Comment by moutikabdessabour** [comment]
Ok sorry for all this confusion. this issue shows up because I'm not calling `tidytable()`

**Comment by markfairbanks** [comment]
Something odd - this issue happens when you use `add_class()`, but not when you use `as_tidytable()`. Maybe because `as_tidytable()` runs it through `as.data.table()` first?

Using `add_class()`:

<img width="944" alt="Screen Shot 2020-09-27 at 3 25 01 PM" src="https://user-images.githubusercontent.com/28766000/94377359-b6cf3900-00d5-11eb-8f59-582a6eaae894.png">

Using `as_tidytable()`:

<img width="941" alt="Screen Shot 2020-09-27 at 3 25 14 PM" src="https://user-images.githubusercontent.com/28766000/94377366-c9e20900-00d5-11eb-8647-1e3d07525ace.png">

**Comment by moutikabdessabour** [comment]
I've been going at a witch hunt for an hour now just for being too lazy to modify the source code of the package.

**Comment by markfairbanks** [comment]
Thanks again for all the help on this! Here's the final version. I used another one of your tricks from above where you were re-classing the object in the print function.

```r
#' @export
print.tidytable <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
  class(x) <- c("paged_df", "tidytable_print", "tidytable", "data.table", "data.frame")
  print(x, ..., n = n, width = width, n_extra = n_extra)
}

#' @export
print.tidytable_print <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
  mat <- trunc_mat(x, n = n, width = width, n_extra = n_extra)
  mat$summary <- unname(mat$summary)
  print(mat)
}
```

This way tidytables don't carry the extra `"paged_df"` class all the time.

**Comment by moutikabdessabour** [comment]
Your welcome it's my pleasure to help. Do you have a linked in or a facebook account I have some questions?

**Comment by markfairbanks** [comment]
Yep - https://www.linkedin.com/in/mark-fairbanks-1819ba155
