### ISSUE TITLE
Referring to another variable in mutate_across.

### ISSUE THREAD

**Issue by luispfonseca** [markfairbanks/tidytable#145]
Thanks once again for all the work for this package.

    library(tidytable)
    #> 
    #> Attaching package: 'tidytable'
    #> The following object is masked from 'package:stats':
    #> 
    #>     dt
    library(tidyverse)

    mtcars <- head(mtcars)

    # Fine
    mtcars %>%
      mutate(mpg = case_when(cyl == 6 ~ 5, TRUE ~ 0))
    #>   mpg cyl disp  hp drat    wt  qsec vs am gear carb
    #> 1   5   6  160 110 3.90 2.620 16.46  0  1    4    4
    #> 2   5   6  160 110 3.90 2.875 17.02  0  1    4    4
    #> 3   0   4  108  93 3.85 2.320 18.61  1  1    4    1
    #> 4   5   6  258 110 3.08 3.215 19.44  1  0    3    1
    #> 5   0   8  360 175 3.15 3.440 17.02  0  0    3    2
    #> 6   5   6  225 105 2.76 3.460 20.22  1  0    3    1
    mtcars %>%
      mutate(mpg = case.(cyl == 6, 5, TRUE, 0))
    #>   mpg cyl disp  hp drat    wt  qsec vs am gear carb
    #> 1   5   6  160 110 3.90 2.620 16.46  0  1    4    4
    #> 2   5   6  160 110 3.90 2.875 17.02  0  1    4    4
    #> 3   0   4  108  93 3.85 2.320 18.61  1  1    4    1
    #> 4   5   6  258 110 3.08 3.215 19.44  1  0    3    1
    #> 5   0   8  360 175 3.15 3.440 17.02  0  0    3    2
    #> 6   5   6  225 105 2.76 3.460 20.22  1  0    3    1

    # Fine
    mtcars %>%
      mutate(across(starts_with("mp"), ~ case_when(. == 6 ~ 5, TRUE ~ 0)))
    #>   mpg cyl disp  hp drat    wt  qsec vs am gear carb
    #> 1   0   6  160 110 3.90 2.620 16.46  0  1    4    4
    #> 2   0   6  160 110 3.90 2.875 17.02  0  1    4    4
    #> 3   0   4  108  93 3.85 2.320 18.61  1  1    4    1
    #> 4   0   6  258 110 3.08 3.215 19.44  1  0    3    1
    #> 5   0   8  360 175 3.15 3.440 17.02  0  0    3    2
    #> 6   0   6  225 105 2.76 3.460 20.22  1  0    3    1
    mtcars %>%
      mutate_across.(starts_with("mp"), ~ case.(. == 6, 5, TRUE, 0))
    #> # tidytable [6 × 11]
    #>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
    #>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
    #> 1     0     6   160   110  3.9   2.62  16.5     0     1     4     4
    #> 2     0     6   160   110  3.9   2.88  17.0     0     1     4     4
    #> 3     0     4   108    93  3.85  2.32  18.6     1     1     4     1
    #> 4     0     6   258   110  3.08  3.22  19.4     1     0     3     1
    #> 5     0     8   360   175  3.15  3.44  17.0     0     0     3     2
    #> 6     0     6   225   105  2.76  3.46  20.2     1     0     3     1

    # Error
    mtcars %>%
      mutate(across(starts_with("mp"), ~ case_when(cyl == 6 ~ 5, TRUE ~ 0)))
    #>   mpg cyl disp  hp drat    wt  qsec vs am gear carb
    #> 1   5   6  160 110 3.90 2.620 16.46  0  1    4    4
    #> 2   5   6  160 110 3.90 2.875 17.02  0  1    4    4
    #> 3   0   4  108  93 3.85 2.320 18.61  1  1    4    1
    #> 4   5   6  258 110 3.08 3.215 19.44  1  0    3    1
    #> 5   0   8  360 175 3.15 3.440 17.02  0  0    3    2
    #> 6   5   6  225 105 2.76 3.460 20.22  1  0    3    1
    mtcars %>%
      mutate_across.(starts_with("mp"), ~ case.(cyl == 6, 5, TRUE, 0))
    #> Error in ~cyl == 6: object 'cyl' not found

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by markfairbanks** [comment]
All set! Thanks for catching this.

``` r
library(tidytable, warn.conflicts = FALSE)

mtcars %>%
  mutate_across.(starts_with("mp"), ~ case.(cyl == 6, 5, TRUE, 0))
#> # tidytable [32 × 11]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1     5     6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2     5     6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3     0     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4     5     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5     0     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6     5     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7     0     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8     0     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9     0     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10     5     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows
```
