### ISSUE TITLE
Retheming the docs

### ISSUE THREAD

**Issue by moutikabdessabour** [markfairbanks/tidytable#164]
Can you give me your feedback on the new ["site"](https://moutikabdessabour.github.io/tidytable/), I can remove the burgundy I was just trying to see how it looks. Also thanks for the warning on the speed comparaisons, I managed to disable the chunks by setting the global knitr options `eval=F`. Also I can find the original logo png I want to make it transparent so the `README` will look nicer in github's dark theme.

![](https://i.imgur.com/9QcoZhu.png)

Nevermind the logo question I managed to find it. Can you link me the tool u used to create the favicons I saw one in an rstudio thread but I can manage to find it now

**Comment by markfairbanks** [comment]
The site looks good! I agree with you, I think it will look good once the burgundy is black.

As far as favicons - you just need to run `pkgdown::build_favicons()` and it will build it from the logo

**Comment by markfairbanks** [comment]
Before you make a PR, I figure I'll go take a look at some theme options. What was the name of the theme you're using [here](https://moutikabdessabour.github.io/tidytable/)?

**Comment by moutikabdessabour** [comment]
I'm using bootswatch's paper theme with some customization in `pkgdown/extra.css`

**Comment by moutikabdessabour** [comment]
@markfairbanks Now I'm ready to make a PR

**Comment by markfairbanks** [comment]
Sounds good, send it over whenever you're ready

**Comment by markfairbanks** [comment]
Actually - I know you mentioned that you are doing some customizations. Is it possible to make the normal font just a point bigger? (Titles look like they're the right size). Might make it look weird.

If it seems like a pain to do no worries, you can make the pull request as is.

**Comment by moutikabdessabour** [comment]
I made them [bigger](https://moutikabdessabour.github.io/tidytable/), if there is any changes that you'd like to see just let me know

**Comment by markfairbanks** [comment]
Sorry I meant the normal font, not the headers!

Want to make a PR after two things are changed:
* Header size back down to what it was before
* Normal text upsized

Thanks again for all the work on this, the site looks much better 👍

**Comment by moutikabdessabour** [comment]
I think I made the font [bigger](https://moutikabdessabour.github.io/tidytable/) probably bigger than what you wanted. Can you check. It was `13px` I changed it to `16px` do you want the text to be the same size it was on the old website `14px`?

**Comment by markfairbanks** [comment]
Hmm yeah I think `16px` is a bit large. `14px` should be good. Can we increase the code font to `14px` as well? It looks like it stayed at `13px`.

The font-size for headers is good now.

**Comment by moutikabdessabour** [comment]
font size 13px : 
![13px](https://i.imgur.com/Z1ledYc.png)
font size 14px :
![14px](https://i.imgur.com/zzYlWzi.png)
I think 13px blends in nicely with the other content, previous size was `12px`

**Comment by markfairbanks** [comment]
> I think 13px blends in nicely with the other content

Yep, I agree. Looks good
