### ISSUE TITLE
Implement extract.()

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#168]

**Comment by moutikabdessabour** [comment]
As we need to get the captured groups `regexpr` provides this info in the attributes of the returned value mainly `capture.start` and `capture.length` then we could use `substr` to get the substring as now we now the start and end of all the groups:
```r
extract. <- function(.df, ...) {
  UseMethod("extract.")
}

extract..data.frame <- function(.df, col, into,
                    regex = "([[:alnum:]]+)",
                    remove = TRUE,
                     ...) {
  
  .df <- as_tidytable(.df)
  .df <- shallow(.df)

  if (missing(col)) abort("col is missing and must be supplied")
  if (missing(into)) abort("into is missing and must be supplied")

  col <- enquo(col)
  eval_quo(.df[, (into) := print(str_extract_groups(!!col, regex))])
  
  if (remove) eval_quo(.df[, !!col := NULL])

  .df[]
}

str_extract_groups <- function(string, pattern){
  groups <- regexpr(pattern, string, perl = TRUE)
  start <- attr(groups, "capture.start")
  end <- start + attr(groups, "capture.length") - 1L 

  none_found <- start == -1 
  start[none_found] <- NA
  end[none_found] <- NA
  map.(1:ncol(start), ~ substr(string, start[, .x], end[, .x]))
}
### making the test_df
x <- paste0(LETTERS, letters, 1:28)[1:10]
data.table(y = c(paste0(x, "-", rev(x)), 1:4)) -> test_df

# extracting two columns
test_df %>% extract.(y, c("A","B"), regex="([[:alnum:]]+)-([[:alnum:]]+)")

# extracting only the first columns
test_df %>% extract.(y, "A", regex="([[:alnum:]]+)")


# extracting only the first columns
test_df %>% extract.(y, "A")
```

**Comment by markfairbanks** [comment]
This looks good so far. I'll try and do a deep dive later today.

Quick notes:
* If you're using `!!enquo(col)` in one step, use the embracing shortcut instead `{{ col }}`.
* If the name "groups" is causing a problem, we can call it ".groups" to reduce the likelihood that the column name is used.
* Should it be `seq_len(ncol(start))` in this call in `str_extract_groups()`?
  + `map.(seq_along(ncol(start)), ~ substr(string, start[, .x], end[, .x]))`

**Comment by moutikabdessabour** [comment]
Thanks for the remarks.
* > * If the name "groups" is causing a problem, we can call it ".groups" to reduce the likelihood that the column name is used.

these kind of problems always throw me off 😄 .

* > Should it be `seq_len(ncol(start))` in this call in `str_extract_groups()`?
> * `map.(seq_along(ncol(start)), ~ substr(string, start[, .x], end[, .x]))`

`seq_along(ncol(start))` will always return `1` as ncol is an integer of length 1. Using `seq_along(start)` will return `1:length(start)` and as matrices are just vectors with `dims` attribute it won't give the correct output thus the need for `seq_len(ncol())` combo

**Comment by markfairbanks** [comment]
Let's use the "safe" method. Honestly on this one I'm not too worried about speed (as long as we're not extremely slow). This is more a function that will be there so people don't need to load `tidyr`.

We'll also need to add the `convert` argument to the function like `tidyr::extract()` has. You'll see how I implemented the same argument in [separate_rows](https://github.com/markfairbanks/tidytable/blob/master/R/separate_rows.R).

**Comment by moutikabdessabour** [comment]
```r

extract..data.frame <- function(.df, col, into,
                    regex = "([[:alnum:]]+)",
                    remove = TRUE, convert = FALSE,
                     ...) {
  
  .df <- as_tidytable(.df)
  .df <- shallow(.df)

  if (missing(col)) abort("col is missing and must be supplied")
  if (missing(into)) abort("into is missing and must be supplied")

  col <- tidytable:::select_vec_idx(.df, {{col}})
  
  groups <- str_extract_groups(.df[[col]], regex, convert)

  if (length(groups) != length(into)) {
    abort(
      glue("`regex` pattern should define {length(into)} groups; {length(groups)} found.")
    )
  }

  .df[, (into) := get("groups", parent.frame(3))]
  
  if (remove) .df[, (col) := NULL]

  .df[]
}

str_extract_groups <- function(string, pattern, convert){
  groups <- regexpr(pattern, string, perl = TRUE)
  start <- attr(groups, "capture.start")
  end <- start + attr(groups, "capture.length") - 1L

  # in order to force substr to return NA when No match is found
  # set the start and end to NA
  none_found <- start == -1 
  start[none_found] <- NA
  end[none_found] <- NA
  #f <- function(x) x
  #if(convert == TRUE) f <- function(x) type.convert(x, as.is = TRUE)
  if(convert == TRUE) lapply(seq_len(ncol(start)), function(.x) type.convert(substr(string, start[, .x], end[, .x]), as.is = TRUE))
  else lapply(seq_len(ncol(start)), function(.x) substr(string, start[, .x], end[, .x]))
}

z <- paste0(rep(paste0(LETTERS, LETTERS, letters), 20), seq_len(20*28))
z <- paste0(z, "-", rev(z), "-", z, "-", rev(z))
dt <- data.table(y=rep(z,100))
microbenchmark::microbenchmark(
    tidyverse_con = extract(dt, y, LETTERS[1:4], regex = "([[:alpha:]]+)(\\d+)-([[:alpha:]]+)(\\d+)", convert = TRUE),
    tidytable_con = extract.(dt, y, LETTERS[1:4], regex = "([[:alpha:]]+)(\\d+)-([[:alpha:]]+)(\\d+)", convert = TRUE),
    tidyverse = extract(dt, y, LETTERS[1:4], regex = "([[:alpha:]]+)(\\d+)-([[:alpha:]]+)(\\d+)"),
    tidytable = extract.(dt, y, LETTERS[1:4], regex = "([[:alpha:]]+)(\\d+)-([[:alpha:]]+)(\\d+)"),
    times=100
)
#> Unit: milliseconds
#>           expr      min       lq     mean   median       uq       max neval cld
#>  tidyverse_con 62.19802 63.46718 72.48692 70.79101 79.75593 101.45014   100   c
#>  tidytable_con 55.76858 58.07559 63.99253 61.11678 67.91196  86.00002   100  b 
#>      tidyverse 39.79660 40.86833 47.40643 44.97643 53.29116  77.46353   100 a  
#>      tidytable 34.36865 36.07911 44.09919 37.24814 47.54186 282.15358   100 a  
```
We get an edge when `convert` is set because we only `lapply` once, we're also faster than tidyr once there are a lot of rows.

**Comment by markfairbanks** [comment]
@moutikabdessabour As always - thanks for all the work on this, it's very much appreciated. As far as the function - I'm going to leave the checks/testing on this up to you since regex isn't an area that I'm good at. Instead I focused on code format. I just made a couple small changes.

Changes:
* Added documentation - I borrowed heavily from `tidyr::extract()` since I'm not a big user of functions like this.
If you see anything you think needs to be changed feel free to.
* Used `..groups` instead of `get("groups", parent.frame(3))`
* Added a `type_convert()` helper that gets defined inside of `str_extract_groups()`. We could define it outside of `str_extract_groups()` if you prefer - I'll leave that decision up to you.

I made a quick checklist if you wouldn't mind making a pull request.

PR Checklist:
* Add `extract.R`
  + Use "Closes #xx" somewhere in the commit message.
* Run `devtools::document()`
* Add `"..groups"` to the `globalVariables()` function inside of `tidytable::package.R`
* Add unit tests
* Run `devtools::test()` - runs unit tests
* Run `devtools::check()` - makes sure everything follows CRAN rules

If you run into any problems you can't figure out from `test()` or `check()` let me know, some of them can be hard to figure out if you haven't seen them before.

```r
#' Extract a character column into multiple columns using regex
#' 
#' @description 
#' Given a regular expression with capturing groups, `extract()` turns each group
#' into a new column. If the groups don't match, or the input is `NA`, the output
#' will be `NA`.
#'
#' @param .df A data.table or data.frame
#' @param col Column to extract from
#' @param into New column names to split into. A character vector.
#' @param regex A regular expression to extract the desired values. There
#' should be one group (defined by `()`) for each element of `into`
#' @param remove If TRUE, remove the input column from the output data.table
#' @param convert If TRUE, runs `type.convert()` on the resulting column.
#' Useful if the resulting column should be type integer/double.
#' @param ... Additional arguments passed on to methods.
#'
#' @export
#'
#' @examples
#' df <- data.table(x = c(NA, "a-b", "a-d", "b-c", "d-e"))
#' df %>% extract.(x, "A")
#' df %>% extract.(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
#'
#' # If no match, NA:
#' df %>% extract.(x, c("A", "B"), "([a-d]+)-([a-d]+)")
extract. <- function(.df, col, into, regex = "([[:alnum:]]+)",
                     remove = TRUE, convert = FALSE, ...) {
  UseMethod("extract.")
}

#' @export
extract..data.frame <- function(.df, col, into, regex = "([[:alnum:]]+)",
                                remove = TRUE, convert = FALSE, ...) {
  
  .df <- as_tidytable(.df)
  .df <- shallow(.df)
  
  if (missing(col)) abort("col is missing and must be supplied")
  if (missing(into)) abort("into is missing and must be supplied")
  
  col <- select_vec_idx(.df, {{col}})
  
  groups <- str_extract_groups(.df[[col]], regex, convert)
  
  if (length(groups) != length(into)) {
    abort(
      glue("`regex` pattern should define {length(into)} groups; {length(groups)} found.")
    )
  }
  
  .df[, (into) := ..groups]
  
  if (remove) .df[, (col) := NULL]
  
  .df[]
}

str_extract_groups <- function(string, pattern, convert){
  groups <- regexpr(pattern, string, perl = TRUE)
  start <- attr(groups, "capture.start")
  end <- start + attr(groups, "capture.length") - 1L
  
  # in order to force substr to return NA when No match is found
  # set the start and end to NA
  none_found <- start == -1 
  start[none_found] <- NA
  end[none_found] <- NA
  
  type_convert <- function(x, .convert = convert) {
    if (.convert) type.convert(x, as.is = TRUE)
    else x
  }
  
  lapply(
    seq_len(ncol(start)),
    function(.x) type_convert(substr(string, start[, .x], end[, .x]))
  )
}
```

**Comment by moutikabdessabour** [comment]
> Used `..groups` instead of `get("groups", parent.frame(3))`
nice trick.
When I looked into the `tidyr` tests I found out that they drop groups with passing `NA` and merge them when they have same name.
Changes :
* removed `type_convert` as it's no longer needed as we need to merge columns based on `name`.
* added default return to `str_extract_groups` as it fails if the regex doesn't define groups.
* added `tidyr` like functionality and documented it in the examples section.

```r
#' Extract a character column into multiple columns using regex
#' 
#' @description 
#' Given a regular expression with capturing groups, `extract()` turns each group
#' into a new column. If the groups don't match, or the input is `NA`, the output
#' will be `NA`. When you pass same name in the into arg it will merge the groups
#' together. Whilst passing `NA` in the into arg will drop the group from the 
#' resulting `tidytable`
#'
#' @param .df A data.table or data.frame
#' @param col Column to extract from
#' @param into New column names to split into. A character vector.
#' @param regex A regular expression to extract the desired values. There
#' should be one group (defined by `()`) for each element of `into`
#' @param remove If TRUE, remove the input column from the output data.table
#' @param convert If TRUE, runs `type.convert()` on the resulting column.
#' Useful if the resulting column should be type integer/double.
#' @param ... Additional arguments passed on to methods.
#'
#' @export
#'
#' @examples
#' df <- data.table(x = c(NA, "a-b-1", "a-d-3", "b-c-2", "d-e-7"))
#' df %>% extract.(x, "A")
#' df %>% extract.(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
#'
#' # If no match, NA:
#' df %>% extract.(x, c("A", "B"), "([a-d]+)-([a-d]+)")
#' # drop columns by passing NA
#' df %>% extract.(x, c("A", NA, "B"), "([a-d]+)-([a-d]+)-(\\d+)")
#' # merge groups by passing same name
#' df %>% extract.(x, c("A", "B", "A"), "([a-d]+)-([a-d]+)-(\\d+)")
extract. <- function(.df, col, into, regex = "([[:alnum:]]+)",
                     remove = TRUE, convert = FALSE, ...) {
  UseMethod("extract.")
}

#' @export
extract..data.frame <- function(.df, col, into, regex = "([[:alnum:]]+)",
                                remove = TRUE, convert = FALSE, ...) {
  
  .df <- as_tidytable(.df)
  .df <- shallow(.df)
  
  if (missing(col)) abort("col is missing and must be supplied")
  if (missing(into)) abort("into is missing and must be supplied")
  
  col <- select_vec_idx(.df, {{ col }})
  
  groups <- str_extract_groups(.df[[col]], regex, convert = convert)
  
  if (length(groups) != length(into)) {
    abort(
      glue("`regex` pattern should define {length(into)} groups; {length(groups)} found.")
    )
  }
  
  keep_group <- !is.na(into)
  groups <- groups[keep_group]
  into <- into[keep_group]

  if(anyDuplicated(into) > 0){
    groups <- lapply(split(groups, into), pmap., paste0, .SIMPLIFY = TRUE)
    into <- names(groups)
  }

  if(convert) groups <- lapply(groups, type.convert, as.is = TRUE)

  .df[, (into) := ..groups]
  
  if (remove) .df[, (col) := NULL]
  
  .df[]
}

str_extract_groups <- function(string, pattern, convert = FALSE){
  groups <- regexpr(pattern, string, perl = TRUE)
  start <- attr(groups, "capture.start")
  end <- start + attr(groups, "capture.length") - 1L
  if(is.null(start)) {
    return(list())
  }
  # in order to force substr to return NA when No match is found
  # set the start and end to NA
  none_found <- start == -1 
  start[none_found] <- NA
  end[none_found] <- NA
  
  lapply(
    seq_len(ncol(start)),
    function(.x) substr(string, start[, .x], end[, .x])
  )
}
```

**Comment by markfairbanks** [comment]
A couple things.

1 - Some small spacing adjustments here to fit the style guide:
```r
if (anyDuplicated(into) > 0) {
  groups <- lapply(split(groups, into), pmap., paste0, .SIMPLIFY = TRUE)
  into <- names(groups)
}

if (convert) groups <- lapply(groups, type.convert, as.is = TRUE)
```

2 - Is .SIMPLIFY so that `pmap.` returns a character vector?

**Comment by moutikabdessabour** [comment]
> 2 - Is .SIMPLIFY so that `pmap.` returns a character vector?
Yes.

**Comment by markfairbanks** [comment]
Sounds good. Everything looks good to me if you want to make a PR

**Comment by moutikabdessabour** [comment]
I'm trying to run checks `devtools::check()` and it's giving me this error
> object 'anti_join' not found whilst loading namespace 'tidytable'

**Comment by markfairbanks** [comment]
Yeah this is one of the errors I was wondering if it would occur. I didn't realize this when I originally switched to the `verb.()` syntax, but sometimes roxygen gets confused by that `.`, and mis-writes the functions in the namespace.

I have a workaround I've used before, but I'm glad you got it all figured out 👍

**Comment by moutikabdessabour** [comment]
I finally got it to check with no warnings

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

although I had to change `vec_c` to `vctrs::vec_c` in `mutate_rowwise.R` even though we import the `vctrs` package, which is weird. these types of errors deterred me from launching my first package on CRAN more than one year ago.

**Comment by markfairbanks** [comment]
> although I had to change vec_c to vctrs::vec_c in mutate_rowwise.R even though we import the vctrs package

Did you update your fork of tidytable before building out `extract.()`? I believe I updated this already. (I made a bunch of changes to `pivot_longer.()` and happened to find it.)

This issue happens because of `eval_quo()`. For some reason freezing the data.table expression (whether using base R's `substitute()` or `rlang::quo()`) causes this issue. Combining that with the `data.table` `[ ]` call causes the issue. You'll see in `mutate.()` I explicitly call `vctrs::vec_recycle()` instead of just `vec_recycle()`. Base R functions you use inside `eval_quo()` don't have to be explicitly called, but all others do.

**Comment by moutikabdessabour** [comment]
Thanks for the explanation. I won't commit the `mutate_rowwise.` change then

**Comment by moutikabdessabour** [comment]
> I solved it, it's maybe due to having `tidyr::extract`

The way I solved it is by running `devtools::document()` or `roxygen2::roxygenize()` in a fresh `R` session, having `tidyverse` loaded is what causes the confusion as `.` is meant to separate the method from the class and because `verb` are registered as `S3methods` it will result in `NAMESPACE` containing:
```r
S3method(anti_join, .default)
```
instead of
```r
S3method(anti_join, .default)
```
