### ISSUE TITLE
rlang support docs

### ISSUE THREAD

**Issue by nick-youngblut** [markfairbanks/tidytable#192]
It would be helpful if there were more docs about rlang support, such as when using `filter.()`: 

```
df <- data.table(x = c(1,1,2), y = c(1,2,3), z = c("a","a","b"))

n_rows <- function(filt_col, data) {
  data %>% 
   filter.(!!rlang::sym(filt_col) == 1) %>% 
    nrow
}

c('x', 'y') %>%
    lapply(n_rows, data=df)
```

**Comment by markfairbanks** [comment]
I think this is more of an rlang/dplyr issue if you're looking for expanded documentation.

In the README I have "rlang can be used to write custom functions with tidytable functions", and I think that be all the documentation I'll have for this. The general idea for rlang is "if it works in dplyr it should work in tidytable".

If you need help with mixing rlang with tidytable feel free to [create a discussion](https://github.com/markfairbanks/tidytable/discussions) and I can help out.

**Comment by nick-youngblut** [comment]
I could add to the README docs if you accept PRs. While the one example in the README is very helpful (thanks for the nice README and function docs!), it doesn't say anything about using `!!rlang::sym()` for use with `filter.()` or possibly with other tidytable functions.

**Comment by markfairbanks** [comment]
As I mentioned above, I think some of this has more to do with rlang docs than tidytable docs. Converting strings to symbols using `sym()` or `syms()` is just another way to deal with symbols - much like `quo()`/`enquo()`.

> I could add to the README docs if you accept PRs

In general I do accept PRs. Let me think on this one for a little bit, and if I decide a change is needed I'll let you know.
