### ISSUE TITLE
Make `count.` consistent with `dplyr::count`

### ISSUE THREAD

**Issue by talegari** [markfairbanks/tidytable#196]
Hi Mark,

Three things:

1. Using 'n' (instead of 'N') as the resulting column name might not surprise the user when porting code (that works with dplyr).
2. Provide options `wt`, `sort`, `name` and optionally `.drop` to be consistent with dplyr. I find these args helpful.
3.  Be strict with name. There should not be a column with the value of name (or 'N'). Currently, we might end up creating duplicate column names.

``` r
pacman::p_load("tidytable", "tidyverse")
iris %>% 
  transmute.(N = Species) %>% 
  count.(N)
#> # tidytable [3 × 2]
#>   N              N
#>   <fct>      <int>
#> 1 setosa        50
#> 2 versicolor    50
#> 3 virginica     50
```

<sup>Created on 2021-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by markfairbanks** [comment]
> 2. Provide options wt, sort, name and optionally .drop to be consistent with dplyr. I find these args helpful.

I can definitely work on adding these.

> 1. Using 'n' (instead of 'N') as the resulting column name might not surprise the user when porting code (that works with dplyr).

This one unfortunately is going to have to stay as is. You are right, it should be "n", but it's been "N" for so long I don't have a good way to change it without breaking existing users tidytable code. It's actually something I've wanted to change, but I don't think I can.

Originally the translation didn't use `tidytable::summarize.()`, and instead used this data.table code:
``` r
pacman::p_load(data.table)

test_df <- data.table(x = c("a", "a", "b"))

test_df[, .N, by = x]
#>    x N
#> 1: a 2
#> 2: b 1
```

As you can see data.table auto-names this column with "N".

**Comment by moutikabdessabour** [comment]
``` r
library(tidytable)
library(rlang)

count..data.frame <- function(.df, ..., wt = NULL, sort = FALSE, name = NULL) {

  .df <- tidytable:::as_tidytable(.df)

  .by <- enquos(...)
  wt <- enquo(wt)
  
  if(quo_is_null(wt)){
    .df <- summarize.(.df, N = .N, .by = c(!!!.by))
  } else {
    .df <- summarize.(.df, N = sum(!!wt), .by = c(!!!.by))
  }
  
  if(sort) {
    .df <- .df[order(-N)]
  }
  
  if(!is.null(name)){
    data.table::setnames(.df, "N", name)
  }

  .df
}

iris %>% count.(Species, wt=Sepal.Length, sort=TRUE, name="Count")
## tidytable [3 × 2]
#   Species    Count
#   <fct>      <dbl>
# 1 virginica   329.
# 2 versicolor  297.
# 3 setosa      250.
```

**Comment by markfairbanks** [comment]
Hey @moutikabdessabour - would you want to make a pull request with this? I have a few small changes. I know we typically hash this out in the issue itself, but it'll probably be easier if I just comment them in the PR.

**Comment by markfairbanks** [comment]
Friendly reminder of the PR checklist (I need to figure out a better place for this haha):

PR Checklist:
* Use "Closes #xx" somewhere in the commit message if it closes an issue. For example "Added this and that. Closes #xx"
* Add or update documentation (if necessary)
* Run `devtools::document()` - updates documentation files
* Update NEWS.md
* Add simple unit tests (if necessary)
* Run `devtools::test()` - runs unit tests
* Run `devtools::check()` - makes sure everything follows CRAN rules
