### ISSUE TITLE
Publish a guide or vignette for developers

### ISSUE THREAD

**Issue by talegari** [markfairbanks/tidytable#197]
Hi Mark,

I have been a regular user of your package since inception. I look forward happy to contribute.
The code seems to be heavily laden with functions from `rlang` and some utilities. Please write a guide so that it can help the fellow developers to contribute, how to structure the code and so on.

**Comment by markfairbanks** [comment]
This is a good idea - I'll work on it.

**Comment by markfairbanks** [comment]
I did a major refactor of the internal tidytable code for v0.6.0 (now on CRAN). It should make the general workflow of each function much more consistent.

I added a couple internal helper functions that should make some of the more confusing tasks easier for a contributor. For example `build_data_mask()` - a contributor no longer has to worry about how to do that, it will be done for them.

I also have comments to generally explain what each internal function does in the `utils` files.

If you have a chance, please take a look over it and see if there are any parts you have specific questions on.

**Comment by markfairbanks** [comment]
@talegari I'm going to close this issue.

Please see the [pull request template](https://github.com/markfairbanks/tidytable/blob/main/.github/pull_request_template.md) for contributor guidelines.

As far as the utils - if you have any questions that the code comments don't cover please let me know.
