### ISSUE TITLE
Do not allow duplicate column names

### ISSUE THREAD

**Issue by talegari** [markfairbanks/tidytable#198]
Hi Mark,

I am aware that `tidytable` class is a thin layer over `data.table` class with pretty printing facility. Would it be a better idea to be stricter by not allowing dupicte column names?

**Comment by markfairbanks** [comment]
I think this is a good idea. From what I can tell it wouldn't be too much work to implement.

Checklist:
- [ ] Add `.name_repair` arg to `as_tidytable()`
- [ ] Add internal `df_name_repair()` at the end of `summarize.()`
