### ISSUE TITLE
`pivot_longer.()`: Unbalanced data doesn't populate NAs correctly when using `".value"` in `names_to`

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#212]
``` r
pacman::p_load(tidytable, tidyverse)

test_df <- tidytable(x_2 = 2, x_3 = 3, y_5 = 5, y_6 = 6)

# Actual
test_df %>%
  pivot_longer.(everything(), names_to = c(".value", "id"), names_sep = "_")
#> # A tidytable: 2 × 3
#>   id        x     y
#>   <chr> <dbl> <dbl>
#> 1 1         2     5
#> 2 2         3     6

# Expected
test_df %>%
  tidyr::pivot_longer(everything(), names_to = c(".value", "id"), names_sep = "_")
#> # A tibble: 4 x 3
#>   id        x     y
#>   <chr> <dbl> <dbl>
#> 1 2         2    NA
#> 2 3         3    NA
#> 3 5        NA     5
#> 4 6        NA     6
```

This one is a bit more difficult. data.table issue 2575 shows that with unbalanced data `data.table::melt()` doesn't work as expected.

**Edit ----------------------------------------------------------------------------------**

New error in the dev version of tidytable to prevent this from occurring silently
``` r
pacman::p_load(tidytable, tidyverse)

test_df <- tidytable(x_2 = 2, x_3 = 3, y_5 = 5, y_6 = 6)

test_df %>%
  pivot_longer.(everything(), names_to = c(".value", "id"), names_sep = "_")
#> Error: `data.table::melt()` doesn't currently support melting of unbalanced datasets.
```

**Comment by moutikabdessabour** [comment]
A workaround would be adding NA columns containing the missing ids. I'll see if I can implement this later today

**Comment by markfairbanks** [comment]
> I'll see if I can implement this later today

Sounds good to me. No rush - I have a feeling this one might take a few attempts. FYI - I just pushed a commit that fixed #211. With the commit I added an error if there is unbalanced data. Naturally we can drop this error if we figure out a good way to deal with this issue.

**Comment by moutikabdessabour** [comment]
I'm sorry I took too much time on this, I was busy the last few days. the way I'm trying to solve this is by getting the `str_extract/str_separate` result and getting the unique values for each resulting column and then expanding the grid then glueing them together.
```r
measure_vars <- c("x_2", "x_3", "y_5", "y_6")
names_sep <- "_"
names_to <- c(".value", "id")

vals <- tidytable::str_separate(measure_vars, into = names_to, sep = names_sep)

expanded <- do.call(expand_grid., lapply(vals, unique))

do.call(glue::glue, c(paste0("{", names(v), "}", collapse=names_sep), expanded)) -> glued

glued
```
```r
x_2
x_3
x_5
x_6
y_2
y_3
y_5
y_6
```
this easily solves the problem when `names_sep` is used, however when using names pattern it becomes a bit tricky because now we need to get the unquoted parentheses `(|)` and replace them with brackets `{|}`, and get rid of quantifiers and character classes.

**Comment by markfairbanks** [comment]
> I'm sorry I took too much time on this, I was busy the last few days

No worries - I have a feeling this issue won't be fixed until after the next CRAN release. This is a pretty difficult problem. To be honest it might not be fixed until data.table fixes the issue themselves.

I'll look over your attempt a bit more in depth at some point over the next week or so and see if I can figure out some things too.

**Comment by moutikabdessabour** [comment]
I'm thinking about taking puting `{.value}`, `{id}`, etc.. in the first measure var name and then use glue to create the missing names.

I found a solution using `regexpr` :
```r
 regexpr(names_pattern, measure_vars[1], perl = TRUE)
```
to get the location of where the parts should be put, i.e the capturing groups.
now I just need to substitute the parts I tried `substr`, and `substring` and they didn't work.

**Comment by markfairbanks** [comment]
This is great, thanks for taking the time to figure it all out!

A few notes:
* Your "id" column had incorrect labels - so I made sure they were correctly labeled. That's something that is new to the dev version of tidytable.
* `glue()` has a `.envir` argument that is really handy - I used it to replace the `do.call()` steps.
* I added a check to see if adding any `NA` columns was necessary. When they weren't data.table was throwing a warning at the `.df[, (na_cols) := NA]` step.
* Earlier today I added list splicing to `expand_grid.()` and `crossing.()`. So I replaced your `do.call(expand.))` with that. I also used `crossing.()` since it's just `expand_grid.()` plus unique plus sort. (The sort isn't really necessary but it won't hurt anything.)
* I changed `vars` to `names_to_setup` to match the current naming conventions in the dev version of `pivot_longer.()`.

And that's about it! Some pretty small things when all is said and done. It passed all tests, but I want to take another look over the next day or two before it's added.

Here's the function. Quick note - I removed all the cast/coerce stuff at the bottom for now so it takes up less space.

### You'll need to install the dev version of tidytable for this to work!

Feel free to poke around with it and see if you find any issues with what I added. In a couple days I'll ping you - if neither of us have found anything wrong I'll ping you and you can send over a PR.

``` r
pacman::p_load(tidytable, rlang, glue, data.table, vctrs)

shallow <- tidytable:::shallow
select_vec_chr <- tidytable:::select_vec_chr
str_separate <- tidytable:::str_separate
str_extract <- tidytable:::str_extract
df_name_repair <- tidytable:::df_name_repair

new_pivot_longer. <- function(.df,
                                     cols = everything(),
                                     names_to = "name",
                                     values_to = "value",
                                     names_prefix = NULL,
                                     names_sep = NULL,
                                     names_pattern = NULL,
                                     names_ptypes = list(),
                                     names_transform = list(),
                                     names_repair = "check_unique",
                                     values_drop_na = FALSE,
                                     values_ptypes = list(),
                                     values_transform = list(),
                                     fast_pivot = FALSE,
                                     ...) {
  .df <- as_tidytable(.df)

  names <- names(.df)

  measure_vars <- select_vec_chr(.df, {{ cols }})

  if (length(measure_vars) == 0) abort("At least one column must be supplied to cols")

  id_vars <- names[!names %in% measure_vars]

  multiple_names_to <- length(names_to) > 1
  uses_dot_value <- ".value" %in% names_to

  variable_name <- "variable"

  if (uses_dot_value) {
    .df <- shallow(.df)
    
    if (!is.null(names_sep)) {
      names_to_setup <- str_separate(measure_vars, into = names_to, sep = names_sep)

      names_glue <- paste0("{", names_to, "}", collapse = names_sep)
    } else if (!is.null(names_pattern)) {
      names_to_setup <- str_extract(measure_vars, into = names_to, names_pattern)

      names_glue <- paste0("{", names_to, "}", collapse = "_")
      new_names <- glue(names_glue, .envir = names_to_setup)
      setnames(.df, measure_vars, new_names)
      measure_vars <- new_names
    } else {
      abort("If you use '.value' in `names_to` you must also supply
            `names_sep' or `names_pattern")
    }
    
    names_to_setup <- crossing.(!!!names_to_setup)
    
    glued <- glue(names_glue, .envir = names_to_setup)
    
    na_cols <- setdiff(glued, measure_vars)
    
    if (length(na_cols) > 0) {
      .df[, (na_cols) := NA]
    }

    .value <- names_to_setup$.value
    v_fct <- factor(.value, levels = unique(.value))

    measure_vars <- split(glued, v_fct)
    values_to <- names(measure_vars)
    names(measure_vars) <- NULL

    if (multiple_names_to) {
      variable_name <- names_to[!names_to == ".value"]
      
      .value_ids <- unique(names_to_setup[[variable_name]])
      .value_ids <- vec_rep_each(.value_ids, nrow(.df))
    }
  } else if (multiple_names_to) {
    if (is.null(names_sep) && is.null(names_pattern)) {
      abort("If you supply multiple names in `names_to` you must also
            supply `names_sep` or `names_pattern`")
    } else if (!is.null(names_sep) && !is.null(names_pattern)) {
      abort("only one of names_sep or names_pattern should be provided")
    }

    variable_name <- paste0(names_to, collapse = "___")
  } else {
    variable_name <- names_to
  }

  .df <- suppressWarnings(melt(
    data = .df,
    id.vars = id_vars,
    measure.vars = measure_vars,
    variable.name = variable_name,
    value.name = values_to,
    ...,
    # na.rm = values_drop_na,
    variable.factor = fast_pivot,
    value.factor = FALSE
  ))
  
  if (!is.null(names_prefix)) {
    .df <- mutate.(.df, !!variable_name := gsub(paste0("^", names_prefix), "", !!sym(variable_name)))
  }

  if (multiple_names_to && uses_dot_value) {
    .df <- mutate.(.df, !!variable_name := !!.value_ids)
  } else if (multiple_names_to && !uses_dot_value) {
    if (!is.null(names_sep)) {
      .df <- separate.(.df, !!sym(variable_name), into = names_to, sep = names_sep)
    } else {
      .df <- extract.(.df, !!sym(variable_name), into = names_to, regex = names_pattern)
    }

    # Put new names before value column
    .df <- relocate.(.df, !!!syms(names_to), .before = !!sym(values_to))
  } else if (!multiple_names_to && uses_dot_value) {
    .df <- mutate.(.df, variable = NULL)
  }

  .df <- df_name_repair(.df, .name_repair = names_repair)
  
  as_tidytable(.df)
}

test_df <- tidytable(x_2 = 2, x_3 = 3, y_5 = 5, y_6 = 6) # Unbalanced
# test_df <- tidytable(x_2 = 2, x_3 = 3, y_2 = 5, y_3 = 6) # Balanced

# Actual
test_df %>%
  new_pivot_longer.(
    everything(), names_to = c(".value", "id"),
    names_sep = "_"
  )
#> # tidytable[,3] [4 × 3]
#>   id        x     y
#>   <chr> <dbl> <dbl>
#> 1 2         2    NA
#> 2 3         3    NA
#> 3 5        NA     5
#> 4 6        NA     6
```

**Comment by markfairbanks** [comment]
FYI - I made some edits to the above function below the `df_name_repair()` call. Nothing that changed the `".value"` part, just some general clean up. Those changes are already pushed to the dev version of tidytable.

**Comment by markfairbanks** [comment]
After some light spot checking, I think I'm good with the function as is. Want to make a PR?

A quick side note though on something I mentioned above

> I also used crossing.() since it's just expand_grid.() plus unique plus sort. (The sort isn't really necessary but it won't hurt anything.)

I actually think this sorting is a good way to make sure the pivoting gets the correct "id" labels when we add them back in later. If they're all in the same order it's much less likely we mess this step up.

The order might be slightly unexpected, but I think it's a good tradeoff.  Here's an example from the data.table issue mentioned above that shows `new_pivot_longer.()` gives the correct values:

``` r
set.seed(2334)
test_df2 <- data.table(
  a_alpha = rnorm(3), a_gamma = rnorm(3),
  b_beta = rnorm(3), b_gamma = rnorm(3),
  groups = c(1:3)
)

test_df2 %>%
  new_pivot_longer.(
    -groups, names_to = c(".value", "labels"), names_sep = "_"
  )
#> # A tidytable: 9 × 4
#>   groups labels      a        b
#>    <int> <chr>   <dbl>    <dbl>
#> 1      1 alpha  -0.118 NA      
#> 2      2 alpha   1.24  NA      
#> 3      3 alpha   0.809 NA      
#> 4      1 beta   NA      1.68   
#> 5      2 beta   NA     -0.574  
#> 6      3 beta   NA     -0.0573 
#> 7      1 gamma  -0.766 -0.706  
#> 8      2 gamma  -0.592  0.00190
#> 9      3 gamma   0.528  1.06

test_df2 %>%
  tidyr::pivot_longer(
    -groups, names_to = c(".value", "labels"), names_sep = "_"
  ) %>%
  dplyr::arrange(labels, groups)
#> # A tibble: 9 x 4
#>   groups labels      a        b
#>    <int> <chr>   <dbl>    <dbl>
#> 1      1 alpha  -0.118 NA      
#> 2      2 alpha   1.24  NA      
#> 3      3 alpha   0.809 NA      
#> 4      1 beta   NA      1.68   
#> 5      2 beta   NA     -0.574  
#> 6      3 beta   NA     -0.0573 
#> 7      1 gamma  -0.766 -0.706  
#> 8      2 gamma  -0.592  0.00190
#> 9      3 gamma   0.528  1.06
```

**Comment by markfairbanks** [comment]
Friendly reminder of the PR checklist:

* Use "Closes #xx" somewhere in one of the commit messages if it closes an issue. For example "Added this and that. Closes #xx"
* Add or update documentation (if necessary)
* Run `devtools::document()` - updates documentation files
* Update NEWS.md
* Add simple unit tests (if necessary)
* Run `devtools::test()` - runs unit tests
* Run `devtools::check()` - makes sure everything follows CRAN rules

**Comment by markfairbanks** [comment]
@moutikabdessabour I ended up adding this so I can start the process of getting v0.6.0 sent to CRAN. I gave you the credit in the NEWS bullet though - thanks again for figuring this out!

**Comment by markfairbanks** [comment]
@marianschmidt If you have any time free would you be able to install the development version of tidytable and see if the new `pivot_longer.()` works correctly for you with `".value"` in `names_to`?  

If you don't have the extra time no worries! It passes the new tests that I made, but I figured I would ping you since you seem to be one of the main users of this functionality.

**Comment by marianschmidt** [comment]
Hi @markfairbanks, sorry that I couldn't react yesterday. So far, I did not detect any issues with the new implementation. All my non-productive tests are working. Thanks.

**Comment by moutikabdessabour** [comment]
I'm sorry I was busy this week. Glad to see that this issue is resolved.
