### ISSUE TITLE
`across.()` can't find newly created columns

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#232]
``` r
pacman::p_load(tidytable)

test_df <- tidytable(
  x = rep(1, 3),
  y = rep(2, 3),
)

test_df %>%
  mutate.(
    double_x = x * 2,
    across.(c(x, double_x), as.character)
  )
#> Error: Can't subset columns that don't exist.
#> x Column `double_x` doesn't exist.
```

**Comment by markfairbanks** [comment]
Notes:
* Only is an issue in `mutate.()`. `arrange.(across.())` and `summarize.(across.())` will work just fine.
* Occurs because `test_df` is passed to `tidytable:::prep_exprs()` before "double_x" is created.
  + Might be able to fix this by looping through the dots? Would potentially very expensive if `.by` is used.

**Comment by moutikabdessabour** [comment]
Correct me if I'm wrong but `prep_expr` only prepares the expression it doesn't evaluate it. We could select the column names based  on the dots' names and column names sparing us from the taxing call to prep_expr each time

**Comment by markfairbanks** [comment]
> We could select the column names based on the dots' names and column names

Unfortunately this fails in the case where the user uses the tidyselect helper `where()`. For example this needs to work (it does now after my most recent updates):

``` r
pacman::p_load(tidytable)

test_df <- tidytable(
  x = rep(1, 3),
  y = rep(2, 3),
)

test_df %>%
  mutate.(
    double_x = x * 2,
    across.(where(is.numeric), as.character)
  )
#> # A tidytable: 3 × 3
#>   x     y     double_x
#>   <fct> <fct> <fct>   
#> 1 1     2     2       
#> 2 1     2     2       
#> 3 1     2     2
```

If we just go by column names `where(is.character)` would miss out on "double_x" since the column doesn't exist in the initial `prep_exprs()`. This is why a loop is needed - you prep the first dot `double_x = x * 2`, evaluate it and add it to the data frame, then you prep/evaluate `across.(where(is.numeric), as.character)`

> sparing us from the taxing call to prep_expr each time

I don't think this is too much of a worry. `prep_exprs()` uses `lapply()` in the background so it's applying to each individual dot separately anyway.
