### ISSUE TITLE
`across.()` in `mutate.()` can't find new columns when `.by` is used

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#233]
``` r
pacman::p_load(tidytable)

test_df <- tidytable(
  x = rep(1, 3),
  y = rep(2, 3),
  z = c("a", "a", "b")
)

test_df %>%
  mutate.(
    double_x = x * 2,
    across.(c(x, double_x), as.character),
    .by = z
  )
#> Error: Can't subset columns that don't exist.
#> x Column `double_x` doesn't exist.
```

Note: The solution that was used for #232 probably shouldn't be used here. Looping through the dots will lead to some large performance issues when `.by` is used.

Short term it's probably safest to only allow `across.()` to be the first dot when `.by` is used. Seems like a pretty edge case usage anyway.

Edit of new error message:
``` r
pacman::p_load(tidytable)

test_df <- tidytable(
  x = rep(1, 3),
  y = rep(2, 3),
  z = c("a", "a", "b")
)

test_df %>%
  mutate.(
    double_x = x * 2,
    across.(c(x, double_x), as.character),
    .by = z
  )
#> Error: across.() can only be used in the first position of mutate.()
#>               when `.by` is used.
```

**Comment by marianschmidt** [comment]
I was wondering, if there would any benefit on adding some comprehensive tests to your package in order to catch such kind of problems when combining multiple tidytable functions.
Unfortunately, I am not an expert on unit tests. I have understood that they should be quite minimal, but I thought, there might be some benefit to also add more complex tests (maybe even just implicit tests by placing sample code in the vignette to show tidytables complex functionality). I think the chance might be higher to catch adverse effects of under the hood changes in the future than if you always have very specific and small unit tests with 2x2 data.

**Comment by markfairbanks** [comment]
If you look [here](https://github.com/markfairbanks/tidytable/tree/main/tests/testthat) you'll be able to see the full range of tests that each function currently has. In all there are about 900 checks run every time I make a change to tidytable.

When you write unit tests they can only check for what you've thought to check for. Having long/complex chains doesn't typically help pinpoint issues. For the most part no issues are really complex, they're simple issues that you can drill down to a simple reproducible example.

As bugs are found I add tests for that specific bug, but there's no way for me to know a bug exists until someone finds it (myself included). This `across.()` bug was something I found just a few hours after the initial implementation. You can [see here](https://github.com/markfairbanks/tidytable/blob/main/tests/testthat/test-across.R) all of the tests currently run for `across.()`.

**Comment by markfairbanks** [comment]
Closing this - as this is going to just be a limitation of tidytable.

Note that `across.()` will work when `.by` is used, but only if it's in the first positon:

``` r
pacman::p_load(tidytable)

test_df <- tidytable(
  x = rep(1, 3),
  y = rep(2, 3),
  z = c("a", "a", "b")
)

test_df %>%
  mutate.(
    across.(c(x, y), ~ .x + 1),
    double_x = x * 2,
    .by = z
  )
#> # A tidytable: 3 × 4
#>       x     y z     double_x
#>   <dbl> <dbl> <chr>    <dbl>
#> 1     2     3 a            4
#> 2     2     3 a            4
#> 3     2     3 b            4
```
