### ISSUE TITLE
Implement `tidytable` methods

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#255]

**Comment by markfairbanks** [comment]
@moutikabdessabour if you want to take a shot at this here is the general idea of the update.

Updated `arrange.()`:
```r
#' @export
arrange..tidytable <- function(.df, ...) {
  dots <- enquos(...)
  if (length(dots) == 0) return(.df)
  dots <- prep_exprs(dots, .df)

  i <- expr(order(!!!dots))

  dt_expr <- call2_i(.df, i)

  eval_tidy(dt_expr)
}

#' @export
arrange..data.frame <- function(.df, ...) {
  .df <- as_tidytable(.df)
  arrange.(.df, ...)
}
```

The environment/data masking issue I mentioned before can be seen if you try and update `mutate.()`.

First you change the current method `mutate..data.frame` to `mutate..tidytable` (just like the `arrange.()` example above). This is what the new `mutate..data.frame` should look like:
```r
#' @export
mutate..data.frame <- function(.df, ..., .by = NULL,
                               .keep = "all", .before = NULL, .after = NULL) {
  .df <- as_tidytable(.df)
  
  mutate.(
    .df, ..., .by = {{ .by }},
    .keep = .keep, .before = {{ .before }}, .after = {{ .after }}
  )
}
```

However when you make this change a bunch of tests start failing because `mutate.()` can no longer find environment variables when operating on data.tables or data.frames. On tidytables they work fine.

All other functions seem to work fine when adding a `.tidytable` method, but data.table handles environments in a weird way with their version of `mutate`. I haven't been able to find a workaround as of yet.

**Comment by moutikabdessabour** [comment]
Ok I basically made the code that creates the `tidytable` functions I will run tests and then look into `mutate`

**Comment by markfairbanks** [comment]
> One easy way to solve this but rather impractical is just to recopy the code into mutate..data.frame this will make the codebase harder to maintain

I think if we do this it will cause issues down the line for anyone making a tidytable subclass that creates their own `mutate.` method. My initial thought is that if this issue can't be solved in another way, we should leave tidytable as is and consider it a limit of the package.

> I think that using a function inside [.data.table i or j component pushes the wanted parent frame two layers up.

What's weird is I don't think this affects any other function except for `mutate.()`. For example in `test-if_all-if_any.R` the test `"can be used in a custom function"` works just fine - and it basically tests the same thing as the failing `across.()` test. So I don't think it affects the `i` component.

I don't think it affects `summarize.()` either but I'd have to check to make sure on that one. So it might not affect everything in the `j` component of `[.data.table` - it might just be a `mutate` issue.

**Comment by moutikabdessabour** [comment]
yeah that's true I can see how that works because mutate i.e `:=` is in of itself a function that's why the outside vars get lost in the call stack, which really should not be an issue due to How R is designed. I remember that we ran into this same issue with `row_number`

**Comment by markfairbanks** [comment]
One way to get around this would be to add an environment argument to `mutate.()`. It would probably also require a check to make sure that no one edits it. Then in the `eval_tidy()` calls we just use the passed environment.

For tidytable subclasses the creator would need to pass on the `caller_env()`.

I'm not sure if I like this workaround or not. Thoughts?

```r
#' @export
mutate..tidytable <- function(.df, ..., .by = NULL,
                              .keep = "all", .before = NULL, .after = NULL,
                              .env = caller_env()) {
  .df <- shallow(.df)

  .by <- enquo(.by)

  dots <- enquos(...)
  if (length(dots) == 0) return(.df)

  mask <- build_data_mask(dots)

  .before <- enquo(.before)
  .after <- enquo(.after)

  needs_relocate <- !quo_is_null(.before) || !quo_is_null(.after)
  if (needs_relocate) {
    original_names <- copy(names(.df))
  }

  if (quo_is_null(.by)) {
    for (i in seq_along(dots)) {
      dots_i <- prep_exprs(dots[i], .df, !!.by)
      dots_i_names <- names(dots_i)

      dots_i <- map2.(dots_i, dots_i_names, ~ mutate_prep(.df, .x, .y))

      j <- expr(':='(!!!dots_i))

      dt_expr <- call2_j(.df, j)

      .df <- eval_tidy(dt_expr, mask, .env)
    }
  } else {
    if (length(dots) > 1) {
      across_flag <- map_lgl.(dots[-1], quo_is_call, "across.")

      if (any(across_flag)) {
        abort("across.() can only be used in the first position of mutate.()
              when `.by` is used.")
      }
    }

    dots <- prep_exprs(dots, .df, !!.by)

    .by <- select_vec_chr(.df, !!.by)

    needs_copy <- any(names(dots) %in% names(.df))
    if (needs_copy) .df <- copy(.df)

    # Check for NULL inputs so columns can be deleted
    null_flag <- map_lgl.(dots, is_null)
    if (any(null_flag)) {
      null_dots <- dots[null_flag]

      dots <- dots[!null_flag]

      j <- call2(":=", !!!null_dots)
      dt_expr <- call2_j(.df, j)

      .df <- eval_tidy(dt_expr, mask, .env)
    }

    if (length(dots) > 0) {
      dots_names <- names(dots)
      assign <- map2.(syms(dots_names), dots, ~ call2("<-", .x, .y))
      output <- call2("list", !!!syms(dots_names))
      expr <- call2("{", !!!assign, output)
      j <- call2(":=", call2("c", !!!dots_names), expr)
      dt_expr <- call2_j(.df, j, .by)

      .df <- eval_tidy(dt_expr, mask, .env)
    }
  }

  if (needs_relocate) {
    df_names <- names(.df)
    new_names <- df_names[df_names %notin% original_names]
    .df <- relocate.(.df, !!!syms(new_names), .before = !!.before, .after = !!.after)
  }

  if (.keep != "all") {
    keep <- get_keep_vars(.df, dots, .by, .keep)
    .df <- .df[, ..keep]
  }

  .df[]
}

#' @export
mutate..data.frame <- function(.df, ..., .by = NULL,
                               .keep = "all", .before = NULL, .after = NULL,
                               .env = caller_env()) {
  .df <- as_tidytable(.df)
  mutate.(
    .df, ..., .by = {{ .by }},
    .keep = .keep, .before = {{ .before }}, .after = {{ .after }},
    .env = .env
  )
}
```

**Comment by moutikabdessabour** [comment]
this is great and we can avoid exposing the environment argument by using a type check and an explicit call to `mutate..tidytable`
``` r
mutate..tidytable <- function(.df, ..., .by = NULL,
                              .keep = "all", .before = NULL, .after = NULL) {
  
  env <- caller_env()

  if(!is_tidytable(.df)){
    .df <- as_tidytable(.df)
    env <- caller_env(2)
  }

  .df <- shallow(.df)

  .by <- enquo(.by)

  dots <- enquos(...)
  if (length(dots) == 0) return(.df)


  mask <- build_data_mask(dots)

  .before <- enquo(.before)
  .after <- enquo(.after)

  needs_relocate <- !quo_is_null(.before) || !quo_is_null(.after)
  if (needs_relocate) {
    original_names <- copy(names(.df))
  }

  if (quo_is_null(.by)) {
    for (i in seq_along(dots)) {
      dots_i <- prep_exprs(dots[i], .df, !!.by)
      dots_i_names <- names(dots_i)

      dots_i <- map2.(dots_i, dots_i_names, ~ mutate_prep(.df, .x, .y))

      j <- expr(':='(!!!dots_i))

      dt_expr <- call2_j(.df, j)

      .df <- eval_tidy(dt_expr, mask, env)
    }
  } else {
    if (length(dots) > 1) {
      across_flag <- map_lgl.(dots[-1], quo_is_call, "across.")

      if (any(across_flag)) {
        abort("across.() can only be used in the first position of mutate.()
              when `.by` is used.")
      }
    }

    dots <- prep_exprs(dots, .df, !!.by)

    .by <- select_vec_chr(.df, !!.by)

    needs_copy <- any(names(dots) %in% names(.df))
    if (needs_copy) .df <- copy(.df)

    # Check for NULL inputs so columns can be deleted
    null_flag <- map_lgl.(dots, is_null)
    if (any(null_flag)) {
      null_dots <- dots[null_flag]

      dots <- dots[!null_flag]

      j <- call2(":=", !!!null_dots)
      dt_expr <- call2_j(.df, j)

      .df <- eval_tidy(dt_expr, mask, env)
    }

    if (length(dots) > 0) {
      dots_names <- names(dots)
      assign <- map2.(syms(dots_names), dots, ~ call2("<-", .x, .y))
      output <- call2("list", !!!syms(dots_names))
      expr <- call2("{", !!!assign, output)
      j <- call2(":=", call2("c", !!!dots_names), expr)
      dt_expr <- call2_j(.df, j, .by)

      .df <- eval_tidy(dt_expr, mask, env)
    }
  }

  if (needs_relocate) {
    df_names <- names(.df)
    new_names <- df_names[df_names %notin% original_names]
    .df <- relocate.(.df, !!!syms(new_names), .before = !!.before, .after = !!.after)
  }

  if (.keep != "all") {
    keep <- get_keep_vars(.df, dots, .by, .keep)
    .df <- .df[, ..keep]
  }

  .df[]
}

#' @export
mutate..data.frame <- function(.df, ..., .by = NULL,
                              .keep = "all", .before = NULL, .after = NULL){
  mutate..tidytable(.df, ..., .by = {{.by}},
                              .keep = .keep, .before = {{.before}}, .after = {{.after}})
}
```

**Comment by markfairbanks** [comment]
> however because I explicitly call mutate..tidytable the .df would still be a subclass of data.frame i.e R doesn't look for the S3method for .df but rather uses the function.

Ah yep that makes sense. I'll have to think about which workaround to go with.

> I too have not used it but I can query the files I modified from git and use styler::style_file on that list.

If it has to operate on the whole file I might not go this route. I think the old code should stay as-is. Only the new methods need to be styled IMO.

> Yes the test for nested data.tables was failing. and it's due to filter being called inside an anonymous function inside map2 and .y was getting lost in the call stack.

Yep you're right. Not sure how I missed this one. I don't think this issue can affect `arrange.()` (since no environment variables can be called), but I would guess that it affects `summarize.()` and I just don't have a test for it that flags it. We'll have to check on this.

**Comment by moutikabdessabour** [comment]
> If it has to operate on the whole file I might not go this route. I think the old code should stay as-is. Only the new methods need to be styled IMO.
I could use the same code I used to create the tidytable methods to extract only the `function` or just do it manually

**Comment by moutikabdessabour** [comment]
- [x] removed the `mutate_across.`, `summarize_across.`, `arrange_across.` `tidytable` methods.
- [x] used new implementation instead of the old one.
- [  ] make sure styling guide follows the tidyverse convention.

**Comment by markfairbanks** [comment]
As I've been trying to figure this one out I realized there are some other areas that the underlying issue impacts.

``` r
pacman::p_load(tidytable)

val_list <- list(2,3)
test_df <- data.table(x = 1:3)

dt_filter <- function(dt, conditions) {
  conditions <- enquo(conditions)
  filter.(dt, !!conditions)
}

lapply(val_list, function(val) dt_filter(test_df, x < val))
#> Error in .checkTypos(e, names_x): Object 'val' not found amongst [x]
```

(Note: This works in dplyr)

When I'm grabbing the environment in `build_data_mask()` it isn't passing everything it needs to (in this case `val`).

The solution I found for the issue above doesn't fix our issue with `tidytable` methods. And the workaround we are looking at for `tidytable` methods doesn't solve the issue above. There is a solution that solves both, but I can't quite figure it out.

I _think_ the general the idea should be:
1) extract the environment from the quosure
2) combine the quosure environment and the caller_env() somehow

I'm missing the best way to do this unfortunately. I thought the data mask would accomplish that, but it's not.

**Comment by markfairbanks** [comment]
Simply extracting the quosure environment and using it as the evaluation environment inside `eval_tidy()` works for `filter` and `summarize`, but causes some weird errors with `mutate`.

First add this to `utils-general.R`
```r
build_dt_env <- function(x, ...) {
  if (length(x) == 0) {
    dt_env <- caller_env()
  } else if (is_quosures(x)) {
    x <- x[[1]]
    dt_env <- get_env(x)
  } else {
    dt_env <- get_env(x)
  }
  env(dt_env, ...)
}
```

Then this is what `filter` becomes:
```r
#' @export
filter..tidytable <- function(.df, ..., .by = NULL) {
  .df <- as_tidytable(.df)

  .by <- enquo(.by)

  dots <- enquos(...)
  if (length(dots) == 0) return(.df)

  dt_env <- build_dt_env(dots)

  dots <- prep_exprs(dots, .df, !!.by)

  i <- expr(Reduce('&', list(!!!dots)))

  if (quo_is_null(.by)) {
    dt_expr <- call2_i(.df, i)

    .df <- eval_tidy(dt_expr, env = dt_env)
  } else {
    .by <- select_vec_chr(.df, !!.by)

    col_order <- names(.df)

    j <- expr(.SD[!!i])

    dt_expr <- call2_j(.df, j, .by)

    .df <- eval_tidy(dt_expr, env = dt_env)

    setcolorder(.df, col_order)
  }

  .df
}

#' @export
filter..data.frame <- function(.df, ..., .by = NULL) {
  .df <- as_tidytable(.df)
  filter.(.df, ..., .by = {{ .by }})
}
```

Passes all tests and also works on the example here https://github.com/markfairbanks/tidytable/issues/255#issuecomment-840721739

Doing this in `mutate` for some reason makes data.table unable to find the base environment, which makes absolutely no sense :joy:

I get this error:

```r
Error: could not find function "["
```

**Comment by markfairbanks** [comment]
Looks like the issue occurred when the quosure environment was the empty environment. `mutate` now works if you define `build_dt_env()` like so:

```r
build_dt_env <- function(x,  ...) {
  if (length(x) == 0) {
    dt_env <- caller_env(2)
  } else if (is_quosures(x)) {
    x <- x[[1]]
    dt_env <- get_env(x)
  } else {
    dt_env <- get_env(x)
  }

  if (identical(dt_env, empty_env())) {
    dt_env <- caller_env(2)
  }

  env(dt_env, ...)
}
```
