### ISSUE TITLE
Allow tidytable subclasses

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#256]
@moutikabdessabour - FYI

Needs to wait on #255.

Also worth considering is what changes might be necessary for `print.tidytable()`

**Comment by moutikabdessabour** [comment]
as to the changes to the `print` method :
```r
print.tidytable <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
   y <- x
   class(x) <- c("paged_df", "tidytable_print", "tbl", class(x))
  print(x, ..., n = n, width = width, n_extra = n_extra)
  invisible(y)
}
```
I just added `y` so the return object will be the same object that was passed in.

If you need help with creating the methods for `tidytable` class I can automate it, as I think there would be no changes needed to the "actual" code.

**Comment by markfairbanks** [comment]
The `print.tidytable()` change looks good to me

**Comment by markfairbanks** [comment]
Another thing to consider - some data.table functions strip subclasses and some don't. `[.data.table` doesn't (which means `mutate`/`filter`/`arrange`/`summarize`/`select` won't strip attributes.

For example:
``` r
pacman::p_load(tidytable)

df <- tidytable(x = 1:3, y = 1:3)

class(df) <- c("tidytable_subclass", class(df))

df %>%
  mutate.(double_x = x * 2) %>%
  class()
#> [1] "tidytable_subclass" "tidytable"          "data.table"        
#> [4] "data.frame"
```

However some other data.table functions do strip subclasses like `rbindlist`, `melt`, and `dcast`. This means that `bind_rows`, `pivot_longer`, and `pivot_wider` will strip tidytable subclasses as well.
``` r
pacman::p_load(data.table, tidytable)

df1 <- tidytable(x = 1:3, y = 1:3)
df2 <- tidytable(x = 1:3, y = 1:3)

# Strips tidytable class
rbindlist(list(df1, df2)) %>%
  class()
#> [1] "data.table" "data.frame"
```

I currently get around this by running `as_tidytable()` after those functions complete. That works fine, but when someone defines a tidytable subclass we would need to make sure the subclass is retained somehow.

**Comment by moutikabdessabour** [comment]
Save the `class(.df)` in a vector and apply it after running those functions.

**Comment by markfairbanks** [comment]
> Save the class(.df) in a vector and apply it after running those functions.

That's much easier than I was thinking 😂

Another thing to look into is [`vctrs::vec_restore()`](https://vctrs.r-lib.org/reference/vec_proxy.html). I haven't looked too much into it. But maybe that's overkill in this use case?

**Comment by markfairbanks** [comment]
I think `vec_restore()` is the way to go. We would also need to fix `as_tidytable()`.

`bind_rows` isn't a great example since technically multiple data frames are input into the function, but dplyr "restores" using the first data frame:
```r
bind_rows. <- function(..., .id = NULL) {
  dots <- list(...)
  dots <- squash(dots)

  if (!all(map_lgl.(dots, is_tidytable))) {
    dots <- map.(dots, as_tidytable)
  }

  first <- dots[[1]]

  out <- rbindlist(dots, idcol = .id, use.names = TRUE, fill = TRUE)

  vec_restore(out, first)
}
```

And it looks like `[.data.table` preserves attributes so this now works:
```r
test_df <- data.table(x = 1:3)

attr(test_df, "test") <- "foo"

test_df %>%
  bind_rows.(test_df) %>%
  mutate.(double_x = x * 2) %>%
  attributes()
```

**Comment by markfairbanks** [comment]
> We would also need to fix as_tidytable().

Actually I'm not sure how careful we need to be here now that we have `tidytable` methods. Even `as_tibble()` overwrites tibble subclasses. Basically the subclass creator needs to make sure their object is a tidytable subclass before ever calling a tidytable function.

For example there's the tsibble package. A tsibble is a tibble subclass:
``` r
pacman::p_load(tsibble, tsibbledata, tidyverse)

example_ts <- tsibbledata::ansett

example_ts %>%
  class()
#> [1] "tbl_ts"     "tbl_df"     "tbl"        "data.frame"
```

However if you call `as_tibble()` it no longer returns a tsibble:
``` r
pacman::p_load(tsibble, tsibbledata, tidyverse)

example_ts <- tsibbledata::ansett

example_ts %>%
  as_tibble() %>%
  class()
#> [1] "tbl_df"     "tbl"        "data.frame"
```

**Comment by markfairbanks** [comment]
Another thought based on the comments above - it might be that implementing tidytable methods covered most of this issue of allowing tidytable subclasses. The last bit would be covered by implementing `vec_restore()` in these functions:
* `bind_cols`/`bind_rows`
  + Note: `bind_cols` uses `vec_cbind()` so it might be unnecessary
* joins
* `pivot_longer`/`pivot_wider`
* `group_split` (maybe?)

**Comment by moutikabdessabour** [comment]
I agree that `vec_restore` is the way to go as the subclass might have it's own attributes that need to be passed out with the object. ()

Plus I think the modification to `print.tidytable` in the `class(x)` line is unnecessary.

**Comment by moutikabdessabour** [comment]
I think that `print.tidytable` should invisibly return the tidytable without modification.

**Comment by markfairbanks** [comment]
> I think that print.tidytable should invisibly return the tidytable without modification.

Ah yep, I forgot about that part
