### ISSUE TITLE
Feature request: Adding .by argument to complete.()

### ISSUE THREAD

**Issue by AndrewKostandy** [markfairbanks/tidytable#266]
Hi, 

Thank you for this great package. It would be great if .by could be added to the "complete." function.

I have a case where my dplyr code was:

``
df %>% 

group_by(id) %>%

complete(date = seq.Date(min(date), today(), by = "day")) %>%

fill(x, y, x, .direction = "down") %>%

ungroup()
``

When I try to do it with tidytable, I am unable to do "complete." by group as it doesn't have a .by argument.

My equivalent tidytable code should be:

``
df %>%

data.table() %>%

complete.(date = seq.Date(min(date), today(), by = "day"), .by = id) %>% # but "complete." has no .by 

fill.(x, y, z, .direction = "down", .by = id) %>%

data.frame()
``

Thanks again.

**Comment by markfairbanks** [comment]
Sounds good - I'll look into this.

**Comment by markfairbanks** [comment]
All set:

``` r
pacman::p_load(tidyverse, tidytable)

df <- data.table(
  id = rep(1:2, each = 2),
  col1 = c("A", NA, "AA", NA),
  col2 = c("B", "C", "BB", "CC")
)

# tidytable
df %>%
  complete.(col1, col2, .by = id)
#> # A tidytable: 8 × 3
#>      id col1  col2 
#>   <int> <chr> <chr>
#> 1     1 <NA>  B    
#> 2     1 <NA>  C    
#> 3     1 A     B    
#> 4     1 A     C    
#> 5     2 <NA>  BB   
#> 6     2 <NA>  CC   
#> 7     2 AA    BB   
#> 8     2 AA    CC

# tidyverse
df %>% 
 group_by(id) %>% 
 complete(col1, col2)
#> # A tibble: 8 x 3
#> # Groups:   id [2]
#>      id col1  col2 
#>   <int> <chr> <chr>
#> 1     1 A     B    
#> 2     1 A     C    
#> 3     1 <NA>  B    
#> 4     1 <NA>  C    
#> 5     2 AA    BB   
#> 6     2 AA    CC   
#> 7     2 <NA>  BB   
#> 8     2 <NA>  CC
```

**Comment by AndrewKostandy** [comment]
That was fast and works like a charm! Thanks Mark.
Do you have an estimate by when this could be in the CRAN version?

**Comment by markfairbanks** [comment]
Yep, no problem!

CRAN recommends that new versions are submitted at most every 30 days or so. My last submission was May 18th, so my next submission will be around June 18th (give or take a couple of days)
