### ISSUE TITLE
mutate. throws error when column is used before deleted with .by

### ISSUE THREAD

**Issue by moutikabdessabour** [markfairbanks/tidytable#271]
```r
library(tidytable)
library(tidyverse)

test_df = data.frame(
  a = 1:3,
  b = 4:6,
  c = 7:9
)

test_df %>% mutate.(d = a+b, a=NULL, .by=c)
#> Error in `[.data.table`(list(b = 4:6, c = 7:9), , `:=`(c("d"), { : 
#>   object 'a' not found

test_df %>% group_by(c)  %>% mutate(d = a+b, a=NULL)
#> # A tibble: 3 x 3
#> # Groups:   c [3]
#>       b     c     d
#>   <int> <int> <int>
#> 1     4     7     5
#> 2     5     8     7
#> 3     6     9     9
```
this caused by the removal the `NULL` columns before calculating the new columns when .by is used. A quickfix would be the following solution:
```r
    if (!all(null_flag)) {
      dots_names <- names(dots)[!null_flag]
      assign <- map2.(syms(dots_names), dots[!null_flag], ~ call2("<-", .x, .y))
      output <- call2("list", !!!syms(dots_names))
      expr <- call2("{", !!!assign, output)
      j <- call2(":=", call2("c", !!!dots_names), expr)
      dt_expr <- call2_j(.df, j, .by)

      .df <- eval_tidy(dt_expr, env = dt_env)
    }

    if (any(null_flag)) {
      null_dots <- dots[null_flag]

      dots <- dots[!null_flag]

      j <- call2(":=", !!!null_dots)
      dt_expr <- call2_j(.df, j)

      .df <- eval_tidy(dt_expr, env = dt_env)
    }
```

However, as you can notice this would result in removing any column that was reassigned after being removed ....
```r
test_df %>% mutate.(d = a+b, a=NULL, a=1, .by=c)
#> # A tidytable: 3 × 3
#>       b     c     d
#>   <int> <int> <int>
#> 1     4     7     5
#> 2     5     8     7
#> 3     6     9     9
```
I think this goes back to the lazy eval in `mutate.` when .by is used. We could speed up lazy eval when `.by` is used by adding a groupid column that will contain the group id using `.GRP` and maybe sorting the .df by this column might make this a bit faster, below is an implementation of this proposed solution:
```r
mutate..tidytable <- function(.df, ..., .by = NULL,
                              .keep = "all", .before = NULL, .after = NULL) {
  .df <- shallow(.df)

  .by <- enquo(.by)

  dots <- enquos(...)
  if (length(dots) == 0) return(.df)

  dt_env <- get_dt_env(dots)

  .before <- enquo(.before)
  .after <- enquo(.after)

  needs_relocate <- !quo_is_null(.before) || !quo_is_null(.after)
  if (needs_relocate) {
    original_names <- copy(names(.df))
  }
  ### #270 modifications
  null_name_flag <- names(dots) == ""

  names(dots)[null_name_flag] <- sapply(dots[null_name_flag], function(.x) expr_name(get_expr(.x)))


  if (!quo_is_null(.by)) {
    .byn <- tidyselect_names(.df, !!.by)
    .df[, ....I := .I ][, ....GRP := .GRP, .byn ]
    setorder(.df, ....GRP)
  }
  
  for (i in seq_along(dots)) {
    dots_i <- prep_exprs(dots[i], .df, !!.by)
  
    dots_i_names <- names(dots_i) 


    dots_i <- map2.(dots_i, dots_i_names, ~ mutate_prep(.df, .x, .y))

    j <- expr(':='(!!!dots_i))
    
    ### if the dot is null and .by is used we should not pass .by
    ### as data.table throws an error
    dt_expr <- call2_j(.df, j,  if (!quo_is_null(.by) && !quo_is_null(dots[[i]])) "....GRP" else NULL)


    .df <- eval_tidy(dt_expr, env = dt_env)
  }

  if (!quo_is_null(.by)) {
    setorder(.df, ....I)
    .df[, c("....GRP", "....I") := NULL]
  }

  if (needs_relocate) {
    df_names <- names(.df)
    new_names <- df_names[df_names %notin% original_names]
    .df <- relocate.(.df, !!!syms(new_names), .before = !!.before, .after = !!.after)
  }

  if (.keep != "all") {
    keep <- get_keep_vars(.df, dots, .by, .keep)
    .df <- .df[, ..keep]
  }

  .df[]
}
```

**Comment by markfairbanks** [comment]
> A quickfix would be the following solution

I sort of like the quickfix even with follow up issue you found.

> We could speed up lazy eval when .by is used by adding a groupid column that will contain the group id using .GRP and maybe sorting the .df by this column might make this a bit faster, below is an implementation of this proposed solution:

I'll have to look at this solution further, but what's the reasoning for sorting the data frame? I think that would be unexpected behavior to the user

**Comment by markfairbanks** [comment]
So you have a couple options posted:
* Option 1: The quickfix
* Option 2: Redefining behavior

**Option 1**
I like this option. The follow-up bug you found is definitely an edge case that we can add an error for.

**Option 2**
I would like to avoid the loop that would cause data.table to recalculate `by` for every column added. That would start to get expensive if the user is adding multiple columns.

**Comment by moutikabdessabour** [comment]
the reasoning behind the sorting is that I think (i don't know if this is the case) the recalculating of by would be less expensive if all the items in the group are grouped together. if only there was a way to pass to data.table the calculated groups this would make it faster.

**Comment by markfairbanks** [comment]
Ah yep that makes sense. I'm still leaning option 1 at the moment

**Comment by moutikabdessabour** [comment]
btw the `dt` is set back to the correct order once the looping is done.

**Comment by markfairbanks** [comment]
> btw the dt is set back to the correct order once the looping is done.

Ah gotcha, I see what you were using `.I` for now.
