### ISSUE TITLE
[New Functionality]: Adding two existing data.table 's functions.

### ISSUE THREAD

**Issue by coforfe** [markfairbanks/tidytable#287]
Hello Mark,

First of all thanks for your excellent package and for keeping a good track of the new functionality included in `data.table`. 

Would it be possible to include within `reexports` set of functions these two `data.table`'s functions?:

- tstrsplit()
- %chin%

Thanks in advance!
Carlos.

**Comment by markfairbanks** [comment]
Hey Carlos - my initial reaction is I can reexport `%chin%` since that would be pretty handy to use in a `filter.()`.

Do you have an example of how you use `tstrsplit()`? Do you currently use it within a `tidytable` function, or is just it something you use when using `data.table`?

**Comment by markfairbanks** [comment]
The reason I ask about `tstrsplit()` is that the most common use I've seen is this one:

``` r
library(data.table)

test_df <- data.table(x = paste(letters[1:3], letters[1:3], sep = "-"))

copy(test_df)[, c("left", "right") := tstrsplit(x, split = "-")][]
#>      x left right
#> 1: a-a    a     a
#> 2: b-b    b     b
#> 3: c-c    c     c
```

Which you can do in tidytable using `separate.()`:
``` r
library(tidytable)

test_df <- data.table(x = paste(letters[1:3], letters[1:3], sep = "-"))

test_df %>%
  separate.(x, into = c("left", "right"), remove = FALSE)
#> # A tidytable: 3 × 3
#>   x     left  right
#>   <chr> <chr> <chr>
#> 1 a-a   a     a    
#> 2 b-b   b     b    
#> 3 c-c   c     c
```

**Comment by coforfe** [comment]
Hi Mark,

Thanks for your reply.

- Good to hear that `%chin%` would be included in your package in the future.
-  Regarding `tstrsplit()`, yes,  I used several times in `data.table`to separate and at the same time `keep`just one of the elements separated with just the same call to this fuction. With your approach, it is also valid, but to do the same, you would need another `select.()` afterwards. No big deal at all, just the interest to do that very compactly and I imagine faster.

Thanks again!
Carlos.

**Comment by markfairbanks** [comment]
I looked into `tidyr::separate()` a bit more and it looks like the functionality exists by specifying `NA` for one of the output columns.

``` r
library(tidyverse)

test_df <- tibble(x = paste(letters[1:3], letters[1:3], sep = "-"))

# Normal usage
test_df %>%
  separate(x, into = c("left", "right"), sep = "-")
#> # A tibble: 3 x 2
#>   left  right
#>   <chr> <chr>
#> 1 a     a    
#> 2 b     b    
#> 3 c     c

# Can drop using NA
test_df %>%
  separate(x, into = c("left", NA), sep = "-")
#> # A tibble: 3 x 1
#>   left 
#>   <chr>
#> 1 a    
#> 2 b    
#> 3 c
```

I'll open another issue to add this functionality to tidytable

**Comment by coforfe** [comment]
Thanks!
I will try it within data.table to see how it behaves in terms of speed.

Thanks again,
Carlos.

**Comment by markfairbanks** [comment]
Added 👍 

``` r
library(tidytable)

test_df <- tidytable(x = 1:3, y = c("a", "b", "c"))

test_df %>%
  filter.(y %chin% c("a", "c"))
#> # A tidytable: 2 × 2
#>       x y    
#>   <int> <chr>
#> 1     1 a    
#> 2     3 c
```

**Comment by markfairbanks** [comment]
@coforfe - I randomly remembered this issue and figured I would let you know - `tidytable` now exports its own version of `%in%` that uses `%chin%` on character vectors, `vctrs::vec_in()` where possible, and then falls back to `base::'%in%'` when necessary. So you can just use `%in%` and `tidytable` will use the fastest version possible.

You can see the code [here](https://github.com/markfairbanks/tidytable/blob/main/R/in-notin.R).

**Comment by coforfe** [comment]
Thanks @markfairbanks !.
