### ISSUE TITLE
imap., iwalk. and sieve.

### ISSUE THREAD

**Issue by AltfunsMA** [markfairbanks/tidytable#308]
I find I use `imap` and particularly `iwalk` from the `purrr` package quite regularly.

Not loading tidyverse packages means you can more easily use autocomplete to get `tidytable` verbs. On that point, it would also be nice (perhaps too niche?) to provide a synonym to `filter.` that is not 'semi-masked' by `stats::filter`: `sieve.` is what comes to mind.

Further to #307, I'd love to be able to replace this common template for many files every day:

```
library(purrr)
library(data.table)
library(tidytable)

very_large_df <-fread(paste0(my_path, "/my_file.csv")) %>% as_tidytable()

<map_chr., filter. select. unnest. ,etc. to your heart's content>

iwalk(processed_df_list, ~fwrite(.x, paste0(my_path, "/", .y, ".csv")`
```

for this:

```
library(tidytable)

very_large_df <-read_delim.(paste0(my_path, "/my_file.csv"))

<map_chr., sieve. select. unnest. ,etc. to your heart's content>

iwalk.(processed_df_list, ~write_delim.(.x, paste0(my_path, "/", .y, ".csv")`

```

**Comment by markfairbanks** [comment]
I'll have to think about this one as well. I created the `map.`/`map2.` variants really early on in tidytable. In hindsight I'm not sure if I would have added them. They're actually wrappers around base R functions that allow you to use purrr's `~ .x` syntax.

My initial thought is that for anything past `map`/`map2` the user should use `purrr`.

**Comment by AltfunsMA** [comment]
Fair enough, I realise there's also all the adverbs like `safely` so it could end up being a rabbit hole... and I could also create my own version of `library(tidyverse)` that attaches my frequently used packages.

I do think `sieve.` or whatever other name would be useful synonym; but perhaps I am too sensitive to autocomplete stuff-ups...! :D

**Comment by markfairbanks** [comment]
> I realise there's also all the adverbs like safely so it could end up being a rabbit hole

Yep, this is what my worry is. After thinking about it I'm going to close this as out-of-scope for tidytable.
