### ISSUE TITLE
Silent failure of group_by argument if typo

### ISSUE THREAD

**Issue by statzhero** [markfairbanks/tidytable#321]
This seems extremely dangerous to me without a warning, even if technically logical.

``` r
library(tidytable)

test_df <- data.table(
  a = 1:3,
  b = 4:6,
  c = c("a", "a", "b")
)

test_df %>%
  mutate.(double_a = a * 2,
          avg_a = mean(a),
          .by = c)
#> # A tidytable: 3 × 5
#>       a     b c     double_a avg_a
#>   <int> <int> <chr>    <dbl> <dbl>
#> 1     1     4 a            2   1.5
#> 2     2     5 a            4   1.5
#> 3     3     6 b            6   3  

test_df %>%
  mutate.(double_a = a * 2,
          avg_a = mean(a),
          by = c)
#> # A tidytable: 3 × 6
#>      a     b c     double_a avg_a by   
#>  <int> <int> <chr>    <dbl> <dbl> <chr>
#>1     1     4 a            2     2 a    
#>2     2     5 a            4     2 a    
#>3     3     6 b            6     2 b    
```

**Comment by markfairbanks** [comment]
The reason it is called `.by` is because it is legitimate to have a column called "by". I think it would be more unexpected for users if this failed.

This occurs for other arguments within `mutate`, even with dplyr. For example you can use the `.before` argument to relocate new columns:

``` r
library(dplyr, warn.conflicts = FALSE)

test_df <- tibble(
  a = 1:3,
  b = 4:6,
  c = c("a", "a", "b")
)

# Using the .before arg
test_df %>%
  mutate(double_a = a * 2,
         .before = b)
#> # A tibble: 3 × 4
#>       a double_a     b c    
#>   <int>    <dbl> <int> <chr>
#> 1     1        2     4 a    
#> 2     2        4     5 a    
#> 3     3        6     6 b

# Using before creates a column
test_df %>%
  mutate(double_a = a * 2,
         before = b)
#> # A tibble: 3 × 5
#>       a     b c     double_a before
#>   <int> <int> <chr>    <dbl>  <int>
#> 1     1     4 a            2      4
#> 2     2     5 a            4      5
#> 3     3     6 b            6      6
```

**Comment by marianschmidt** [comment]
Why do you think this would be dangerous? Isn't the result very obviously something different than intended. Dimensions of the tidytable are different and you get an additional variable named `by`. Of course there could be a warning for any variable named like an argument, but I guess already `before` and `after` could be intended variable names and a warning, or even a message would probably be annoying and surprising to most users. Does the `tidyverse` have any similar warnings?

**Comment by statzhero** [comment]
This is of course born from personal experience, where datasets have hundreds of variables and dimensions are fluctuating. Note how `avg_a` has different values in both cases, potentially undermining all analysis, which for a misspecified `.before` or `.after` would not matter. 

My suggestion is a warning á la `all_of`, but it is up to you as the project maintainer: 

``` r
var <- c("a", "b")
test_df %>% dplyr::select(var)
Note: Using an external vector in selections is ambiguous.
ℹ Use `all_of(var)` instead of `var` to silence this message.
ℹ See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
```

**Comment by markfairbanks** [comment]
I'm going to leave this one without a warning. I think in this case it's up to the user to ensure they use `.by` instead of `by`.
