### ISSUE TITLE
Implement `tribble.()`

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#335]
Should we implement `tribble.()`? And if so, what should it be called?

First pass at the function.

``` r
pacman::p_load(tidytable, rlang)

tribble. <- function(...) {
  dots <- list2(...)
  name_bool <- map_lgl.(dots, is_bare_formula)
  col_names <- map.(dots[name_bool], ~ as_name(f_rhs(.x)))
  num_cols <- length(col_names)
  dots <- dots[!name_bool]
  dots_length <- length(dots)
  l <- vector("list", num_cols)
  names(l) <- col_names
  for (i in seq_len(num_cols)) {
    locs <- seq(i, dots_length, num_cols)
    l[[i]] <- do.call("c", dots[locs])
  }
  new_tidytable(l)
}

tribble.(
  ~ x, ~ y, ~ z,
  1, 2, "c",
  1, 2, "c",
  1, 2, "c"
)
#> # A tidytable: 3 × 3
#>       x     y z    
#>   <dbl> <dbl> <chr>
#> 1     1     2 c    
#> 2     1     2 c    
#> 3     1     2 c
```

**Comment by markfairbanks** [comment]
I've decided this one won't be implemented. If someone finds this and wants it implemented feel free to comment and I'll reopen the issue.

**Comment by bnicenboim** [comment]
Hi, I actually want this :)
I wanted to create a table manually for rmarkdown, and I was looking for this.

I ended up doing the following, but it would be nice to just have `tribble.()`
```{r}
tb <- bind_rows(c(1,2),
                             c(2,3)) 
colnames(tb) <- c("A","B")
```

**Comment by markfairbanks** [comment]
Any ideas on the name? I’m leaning `tribble()`, but at the same time there is no `tibble()` function in tidytable. Instead you use `tidytable()`.

**Comment by markfairbanks** [comment]
> I guess transposed_tidytable() is too verbose, right?

Yeah, it probably is. And `tridytable()` is a pretty bad name lol.

> But to be honest, the first thing I did was to check for a `tribble()` function in the package...

Yeah I think `tribble()` is probably the best option.

**Comment by erdeyl** [comment]
Tidytribble :)

**Comment by markfairbanks** [comment]
All set! Thanks for the name suggestions - I ended up going with `tribble()`.

``` r
pacman::p_load(tidytable)

tribble(
  ~ x, ~ y,
  "a", 1,
  "b", 2,
  "c", 3
)
#> # A tidytable: 3 × 2
#>   x         y
#>   <chr> <dbl>
#> 1 a         1
#> 2 b         2
#> 3 c         3
```

**Comment by bnicenboim** [comment]
Waw, thanks! You're amazing!
