### ISSUE TITLE
across. inside rowSum functions not working

### ISSUE THREAD

**Issue by bnicenboim** [markfairbanks/tidytable#346]
Hi, me again :)

```
df <- data.frame(x=rep("a", 100), y = 1:100, z = 1:100)

df %>%  dplyr::mutate(total = rowSums(dplyr::across(where(is.numeric))))
df %>%  tidytable::mutate.(total = rowSums(across.(where(is.numeric))))
```

The first one works in dplyr (it's one of their examples in https://dplyr.tidyverse.org/articles/rowwise.html), but doesn't work in tidytable. I get:

`Error in rowSums(list(y = y, z = z)) : 
  'x' must be an array of at least two dimensions`

**Comment by markfairbanks** [comment]
I'll look into it, but this might be a use case outside of what tidytable can do.

**Comment by bnicenboim** [comment]
Also this is not working in the same way. 
```
df %>%  dplyr::mutate(new = across(where(is.numeric)))
df %>%  tidytable::mutate.(new = across.(where(is.numeric)))
```

It seems that `across` without `.fns` is doing `cbind` in dplyr. I tried this below, but it's not working either.
 
```
df %>%  tidytable::mutate.(total = rowSums(across.(where(is.numeric),.fns =  cbind) ))
```

while this works:

```
df %>%  dplyr::mutate(total = rowSums(dplyr::across(where(is.numeric), cbind)))
```

I hope you can find an easy fix!

**Comment by markfairbanks** [comment]
Thanks for documenting these. At the moment anything where `across.()` is used inside of a named mutate will fail.

Will work:
```r
df %>% mutate.(across.())
```

Will fail:
```r
df %>% mutate.(new_col = across.())
```

**Comment by markfairbanks** [comment]
Is there any use case for this when `.by` is used?

**Comment by bnicenboim** [comment]
No, i can't imagine how grouping could be relevant, since the operation is
row wise anyways.

**Comment by markfairbanks** [comment]
All set. Thanks again for catching all of these.

``` r
library(tidytable, warn.conflicts = FALSE)

df <- tidytable(x = rep("a", 5), y = 1:5, z = 1:5)

df %>%
  mutate.(total = rowSums(across.(where(is.numeric))))
#> # A tidytable: 5 × 4
#>   x         y     z total
#>   <chr> <int> <int> <dbl>
#> 1 a         1     1     2
#> 2 a         2     2     4
#> 3 a         3     3     6
#> 4 a         4     4     8
#> 5 a         5     5    10
```

**Comment by bnicenboim** [comment]
amazing, thanks!
It's not too terrible, but for completeness, this doesn't work:
```
df %>%   mutate.(rowSums(across.(where(is.numeric))))
```

**Comment by markfairbanks** [comment]
Ah yep - should have thought about this case. I'll open another issue.
