### ISSUE TITLE
across. doc

### ISSUE THREAD

**Issue by nick-youngblut** [markfairbanks/tidytable#355]
`mutate_across.()` is depreciated:

```
Warning message:
`mutate_across.()` was deprecated in tidytable 0.6.4.
Please use `mutate.(across.())
```

However, `mutate.(across.(where(is.numeric)))` doesn't work, while `mutate_across.(where(is.numeric))` still works (but depreciated). `mutate.(across.(is.numeric))` does not work. It would help to include more docs on how to use `across.()` with `mutate.()`.

I'm using `tidytable=0.6.7`

**Comment by markfairbanks** [comment]
Do you have an example that doesn't work? Everything works on examples that I try.

``` r
library(tidytable, warn.conflicts = FALSE)

df <- data.table(
  x = rep(1, 3),
  y = rep(2, 3),
  z = c("a", "a", "b")
)

df %>%
  mutate.(across.(where(is.numeric), ~ .x * 1))
#> # A tidytable: 3 × 3
#>       x     y z    
#>   <dbl> <dbl> <chr>
#> 1     1     2 a    
#> 2     1     2 a    
#> 3     1     2 b
```

**Comment by nick-youngblut** [comment]
It was due to a typo on my part. I should have checked with a simple reprex. My bad
