### ISSUE TITLE
 tidytable working together with disk.frame

### ISSUE THREAD

**Issue by bnicenboim** [markfairbanks/tidytable#357]
Hi!
I see that the branch got stuck here for quite some time:
https://github.com/xiaodaigh/disk.frame/pull/271#issuecomment-957242028

I was wondering if this will happen in the near future (or if I will have to code much more to have my package compatible with disk frame :/  )

**Comment by markfairbanks** [comment]
[Also worth noting.](https://twitter.com/evalparse/status/1488817214417694723)

**Comment by markfairbanks** [comment]
Looks like `disk.frame` has been [soft deprecated](https://github.com/DiskFrame/disk.frame#notice) and won’t be adding any new features.
