### ISSUE TITLE
Global option to use functions without the dot

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#374]
@leungi @bnicenboim @moutikabdessabour @talegari @nick-youngblut @davidtcaldwell @AltfunsMA

Anyone have any thoughts on this? Good idea? Bad idea?

Setting `options(tidytable_no_dot = TRUE)` would allow the use of tidytable functions without the dot. Note the use of `arrange()` & `summarize()` instead of `arrange.()` & `summarize.()`.

``` r
options(tidytable_no_dot = TRUE)
library(tidytable, warn.conflicts = FALSE)

df <- tidytable(x = 1:3, y = 1:3, z = c("a", "a", "b"))

df %>%
  arrange(x, y) %>%
  summarize(mean_x = mean(x),
            count = n(),
            .by = z)
#> # A tidytable: 2 × 3
#>   z     mean_x count
#>   <chr>  <dbl> <int>
#> 1 a        1.5     2
#> 2 b        3       1
```

You can test out the functionality by running:

``` r
devtools::install_github("markfairbanks/tidytable@no-dot")
```

The basic idea is to give users the ability to use the functions without the dot, but to require an extra step of explicitness since it would overwrite a lot of tidyverse functions.

Another option would be to always export these functions without requiring the user to use `options(tidytable_no_dot = TRUE)`, but this might cause unexpected issues with new users who aren't used to `.by`. Overall the global option feature seems a little safer.

**Comment by AltfunsMA** [comment]
Thanks @markfairbanks , this is a great idea! 

I think the global option feature has clear advantages and almost no drawbacks, particularly for brand new projects/scripts.

Currently, typing tidytable functions in Rstudio is a bit painful with autocomplete always putting the equivalent tidyverse function as the first choice. I also never remember what exact tidyverse packages do what and which functions are available as tidytable, so I'd rather just `options(tidytable_no_dot = TRUE); pacman::p_load(tidyverse, tidytable)` and type away without worries, while still having a clear warning at the top of the script that grouping should be done the data.table way. 

If you already have a mix of tidyverse and tidytable in your project, this could be a bit more of a pain, but you can simply not activate it, or simply make sure you load packages in this order: `pacman::p_load(tidytable, tidyverse)`. That's something you could easily do in a bunch of scripts.

For always re-exporting, I think you'd need (at least) the ability for tidytable functions to fall back to tidyverse ones when passed a `grouped_tbl` or something like that. Not sure this is feasible.

**Comment by bnicenboim** [comment]
I think it's a great idea and I would go further by adding a `group_by()` function. That function could just add an attribute to the data table, such as `group = c("group1","group2"...)`, and then `summarize` and `mutate` could read it unless `.by` is specified.

**Comment by markfairbanks** [comment]
As I think about this one some more - one possible negative to the `options()` path is that it would work well for interactive analysis but limit package development using tidytable. As far as I can tell there wouldn't be a way to use the dotless versions in a package without altering the global options, which isn't recommended.

> I would go further by adding a `group_by()` function

I'll open another issue with this. It is definitely tied to this issue, but I think it is worth a separate discussion. Adding `group_by()` might split the users between two uses for grouping. Not sure if that's good or bad to be honest.

**Comment by markfairbanks** [comment]
Another possibility is to have an option that is the opposite. Something like `options(tidytable_only_dot_funs = TRUE)` so that people can optionally hide the dotless versions.

This could be emphasized by a package startup message:

``` r
library(tidytable, warn.conflicts = FALSE)
#> As of tidytable v0.8.0 functions like `mutate.()` are also exported as `mutate()`.
#>   To disable this behavior set `options(tidytable_only_dot_funs = TRUE)`
```

**Comment by markfairbanks** [comment]
Btw everyone feel free to let me know if you think an idea is bad 😄 I'm open to all ideas and feedback at this point.

**Comment by bnicenboim** [comment]
> @bnicenboim - you've done package development with tidytable. Would you want to be able to use the dotless versions? Would it be confusing to be able to use the dotless versions for analysis but not in a package?

Well, not to me, because now I know it, and I wasn't planning to change the code of the package :)
But now that you mention it, it would be totally confusing if I'm used to use the non dot version and suddenly it doesn't work in a package.

This is a good idea:

> This could be emphasized by a package startup message:

**Comment by markfairbanks** [comment]
> For always re-exporting, I think you'd need (at least) the ability for tidytable functions to fall back to tidyverse ones when passed a grouped_tbl or something like that. Not sure this is feasible.

@AltfunsMA Unfortunately this can't work - for data.table/tidytable functionality to work it must be converted to a data.table first.

**Comment by talegari** [comment]
@markfairbanks  IMHO, there should not be `not-dot` at all. 

1. `R` is already infamous for cluttering the namespace with letting packages load functions with same names which can break the code in unexpected ways ([box](https://github.com/klmr/box) is still far away from being mainstream). I use `tidytable` in production code along with `tidyverse`, I can see this can be a recipe for disaster. For a user, functions ending with dot makes it clear that  the function is coming from `tidytable` and not the `tidyverse` family.

2. `tidytable` lets the user express `group_by` operations with `.by` without creating a intermediate `grouped` dataframe which greatly simplifies things. Again IMHO, this differentiates `tidytable` from `dtplyr` (and others) and this should be maintained as-is.

3. IMHO, `tidytable` must not strive to be a drop-in replacement for `tidyverse`. There will be differences like `tidytable::count` creating `N` (as opposed to `n`).

**Comment by davidtcaldwell** [comment]
For what it's worth, I also find the dots useful in distinguishing tidytable functions from tidyverse and don't find it too painful navigating to the second autocomplete entry in RStudio. I guess there is no harm in having the option to activate a rule like this. I'm still using tidytable with some tidyverse in my code so probably wouldn't use it, however.

**Comment by markfairbanks** [comment]
Thanks for the feedback everyone. As I thought through everything I think I'm going to keep tidytable as-is.

I think overwriting tidyverse functions with the dotless versions would be a pretty unexpected change at this point and could lead to too many issues in user's code. And allowing an `options()` to allow dotless versions could lead to some confusion as well as it wouldn't be usable for package development.
