### ISSUE TITLE
Is it support .data in package？

### ISSUE THREAD

**Issue by ShixiangWang** [markfairbanks/tidytable#38]
If I use this tool in pkg development，How can I avoid variable name not defined？

**Comment by markfairbanks** [comment]
Though tidytable works with rlang's quoting/unquoting, it won't work with more advanced cases like the example you gave

**Comment by ShixiangWang** [comment]
Thanks.

**Comment by markfairbanks** [comment]
Do you have an example where this is necessary? It would be useful to have an example so that I could work on integrating something like that into the package
