### ISSUE TITLE
[New Functionality]: Add two existing functions from tibble.

### ISSUE THREAD

**Issue by coforfe** [markfairbanks/tidytable#391]
Hi Mark,

I think it would be very nice to include two existing functions in `tibble` into `tidytable`.

I often need to include as a new column/s that are included as _rownames_. The output of some functions end up in a data.frame with _rownames_ instead of having that  info as a column. I had less cases in other way around i.e. converting _colnames_ into _rownames_.

To manage that, you can use two very handy functions from `tibble`:

- _rownames_to_column()_
- _column_to_rownames()_

This is an example:

```r

m2 <- cbind(1, 1:4)
colnames(m2, do.NULL = FALSE)
colnames(m2) <- c("x","Y")
rownames(m2) <- rownames(m2, do.NULL = FALSE, prefix = "Obs.")
m2 <- as.data.frame(m2)
rownames(m2)
```
That is the output:

```r
      x Y
Obs.1 1 1
Obs.2 1 2
Obs.3 1 3
Obs.4 1 4
```
To convert the _rownames_ to a new column, you can do that in this way:

```r
library(tibble)
library(tidytable)
m2 %>% 
  rownames_to_column( var = "mynewcol") %>%
  separate.( mynewcol, into = c("c1", "c2"), sep = ".")
```
That produces this output:

```r
# A tidytable: 4 × 4
      x     Y c1    c2   
  <dbl> <dbl> <chr> <chr>
1     1     1 Obs   1    
2     1     2 Obs   2    
3     1     3 Obs   3    
4     1     4 Obs   4    
```

Having the possibility to get the rownames directly within a _mutate.()_ step, would be helpful.

Thanks,
Carlos.

**Comment by markfairbanks** [comment]
Hey Carlos - `data.table` doesn't support row names so it's not possible to have a `column_to_rownames()`.

For `rownames_to_column()` I think the easiest thing would be to utilize functionality that exists within `as_tidytable()`:

``` r
library(tidytable, warn.conflicts = FALSE)

m2 <- cbind(1, 1:4)
colnames(m2) <- c("x","Y")
rownames(m2) <- rownames(m2, do.NULL = FALSE, prefix = "Obs.")
m2 <- as.data.frame(m2)

# Auto-named
m2 %>%
  as_tidytable(.keep_rownames = TRUE)
#> # A tidytable: 4 × 3
#>   rn        x     Y
#>   <chr> <dbl> <dbl>
#> 1 Obs.1     1     1
#> 2 Obs.2     1     2
#> 3 Obs.3     1     3
#> 4 Obs.4     1     4

# Specify a new name
m2 %>%
  as_tidytable(.keep_rownames = "mynewcol")
#> # A tidytable: 4 × 3
#>   mynewcol     x     Y
#>   <chr>    <dbl> <dbl>
#> 1 Obs.1        1     1
#> 2 Obs.2        1     2
#> 3 Obs.3        1     3
#> 4 Obs.4        1     4
```

**Comment by coforfe** [comment]
Hi Mark,

Thanks for explanation!.
Yes, your approach is perfect.

Thanks again,
Carlos.
