### ISSUE TITLE
Include polars in speed comparisons alongside pandas

### ISSUE THREAD

**Issue by exsell-jc** [markfairbanks/tidytable#428]
I noticed that `pandas` is included in the comparisons.

You can see `polars` and `data.table` benchmarks, along with several others, compared here: https://h2oai.github.io/db-benchmark

I thought it would be nice to include them as well.

**Comment by markfairbanks** [comment]
I'll look at adding `polars` for sure. AFAIK it's faster than `data.table` and definitely useful to see.

I'll have to think about adding `tidypolars`. It might be good to add to advertise its existence, but it also has a relatively small user base at the moment.

**Comment by exsell-jc** [comment]
I don't know if I would call it advertising; I think it would help people make decisions on trying/switching over to `tidypolars` or not. It's purely benchmarking (not people with smiling faces with some product discounted at some price :D). Personally, I would even love benchmarks with different hardware like Hardware Unboxed on YouTube.
