### ISSUE TITLE
mutate_rowwise. with keep or transmute_rowwise.

### ISSUE THREAD

**Issue by bnicenboim** [markfairbanks/tidytable#438]
It would be nice to have the `keep `option with `mutate_rowwise.` or to have a `transmute_rowwise.`. I need to use rowwise and `c_across.` when I have lots of columns and so it would be good to be able to get rid of them in one line.

**Comment by markfairbanks** [comment]
Should be an easy enough addition - `mutate_rowwise.` uses `mutate.` in the background

**Comment by markfairbanks** [comment]
@bnicenboim - All set.

``` r
pacman::p_load(tidytable)

df <- data.table(x = 1:3, y = 1:3 * 2, z = c("a", "a", "b"))

df %>%
  mutate_rowwise.(row_mean = mean(c_across.(where(is.numeric))),
                  .keep = "used",
                  .before = x)
#> # A tidytable: 3 × 3
#>   row_mean     x     y
#>      <dbl> <int> <dbl>
#> 1      1.5     1     2
#> 2      3       2     4
#> 3      4.5     3     6
```

**Comment by bnicenboim** [comment]
thanks!
