### ISSUE TITLE
Rename functions?

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#44]
@leungi @RossKen 

I wanted to get some opinions on something. I think I want to rename all of the functions. The `dt_` prefix starts to get clunky after a while. Example:

```r
test_df %>%
  dt_select(dt_starts_with("x"), dt_ends_with("y")) %>%
  dt_arrange(x)
```

That's a bit tough to read.

So this is what I'm thinking about doing:

```r
test_df %>%
  select.(starts_with.("x"), ends_with.("y")) %>%
  arrange.(x)
```

or

**Edit:** As I do more research, functions that start with "." are supposed to be for internal use only. So it would have to be `select.()`.
```r
# Edit: ignore, this isn't allowed
test_df %>%
  .select(.starts_with("x"), .ends_with("y")) %>%
  .arrange(x)
```

I would keep the old ones in the package for a while, but all documentation would use the "dot" version.

If there was a time to do this, it would be now when the user base was still a bit smaller.

Good idea? Bad idea? Is there another way to rename them that I’m not thinking of?

**Comment by leungi** [comment]
@markfairbanks: thanks for keeping me in mind 😃 

The `.*` prefix is brilliant! It resembles the `data.table` syntax closely (e.g., `.N`, `.SD`, `.(...)` when selecting multiple columns).

Bonus for me: it passes the default [styler](https://github.com/r-lib/styler) settings, unlike, say `{.}`.

Also, if you may, I volunteer to help update the docs, as time permits. For example, I almost filed an issue when `dt_summarise()` `group` args didn't work, until I realized my version was out of date 😅

**Comment by markfairbanks** [comment]
As I do more research, functions that start with "." are supposed to be for internal use only. So it would have to be `select.()`. Thoughts on that one? As a user, would you use:
```r
test_df %>%
  select.(starts_with.("x"), ends_with.("y"))
```

or

```r
test_df %>%
  dt_select(dt_starts_with("x"), dt_ends_with("y"))
```

Also if I do make the change, I'll let you know. It would be great to have some help on the documentation

**Comment by leungi** [comment]
I'd go with _`verb.`_ for these reasons:

1. similar starting point as `tidyverse`, user just add a `.`
2. `select_` is taken by `tidyverse`
3. less typing, of course 🙂

**Comment by markfairbanks** [comment]
Awesome - this is where my thinking was as well. I just wanted to make sure it made sense before I started changing everything.

Thanks again for all of the help @leungi

**Comment by leungi** [comment]
Credit all yours; glad I was of use.

**Comment by markfairbanks** [comment]
How should I rename `dt_get_dummies()`?
1. `get_dummies()`
2. `get_dummies.()`

Should the "." syntax only be used for functions that replicate the tidyverse? Or should the "." always be used for consistency?

**Comment by leungi** [comment]
I'd say keep the `.` for consistency.

If verbosity is a concern, some suggestions:

- `dummify.()`
- `dummy.()`
- `dummies.()`

**Comment by leungi** [comment]
Also, congratulations on your `tidytable` mention in [2020-02 Top 40 New R Packages](https://rviews.rstudio.com/2020/03/26/february-2020-top-40-new-r-packages/?mkt_tok=eyJpIjoiTkRZeVptRTJPR1kxWkdWayIsInQiOiJDKzFJYXhqQXRmSHJFUG5RMVNSMzEzaU9DZzZKUlNYWHhnKzVBZmt3TXNvdW5ueng5cklwV1VPN0N4VWRyV2tpbHhPQkdHXC8wNVFkWUl5U0lwanptbDgwWGFvaUZObU1tUVwvRE9UQnhMQit0Z2VDQm55RE5KR0NRbDJFWmdTMWNJIn0%3D) 👏
