### ISSUE TITLE
lag. calling shift

### ISSUE THREAD

**Issue by bnicenboim** [markfairbanks/tidytable#445]
me again :)
Maybe it makes sense to have a function `lag.` calling `data.table::shift`?

**Comment by markfairbanks** [comment]
You can use `lags.` to do this 😄

https://markfairbanks.github.io/tidytable/reference/lags..html

I couldn’t use `lag.` as a name because R was trying to use method dispatch with the base R `lag` so I had to add an “s” at the end of the name.
