### ISSUE TITLE
unite? 

### ISSUE THREAD

**Issue by nick-youngblut** [markfairbanks/tidytable#47]
How should one implement `tidyr::unite()` with tidytable? I don't see any equivalent function in [the docs](https://markfairbanks.github.io/tidytable/)

**Comment by markfairbanks** [comment]
Currently there's no `unite()` translation, but I can get that added today.

In the meantime, this would be the workaround:

``` r
library(tidytable)

test_df <- tidytable(x = 1:3, y = c("a", "b", "c"), z = c("a", "b", "c"))

test_df %>%
  mutate.(new_col = paste(y, z, sep = "_")) %>%
  select.(-y, -z)
#>        x new_col
#>    <int>   <chr>
#> 1:     1     a_a
#> 2:     2     b_b
#> 3:     3     c_c
```

**Comment by nick-youngblut** [comment]
Thanks! I thought that it would be more complicated than a simple `paste()`

**Comment by markfairbanks** [comment]
All set
