### ISSUE TITLE
parallelizing across.

### ISSUE THREAD

**Issue by bnicenboim** [markfairbanks/tidytable#499]
Hi, I was wondering if it's feasible to have the options to parallelize `across.` calls?
Here they show parallelizing with wrapr:
https://win-vector.com/2018/07/08/speed-up-your-r-work/

Maybe something like this could be implemented?

**Comment by markfairbanks** [comment]
Any reason you're looking to parallelize `across.()` in particular? Are you using it with `mutate.()` or `summarize.()`

**Comment by bnicenboim** [comment]
Well, with `across` I do the same thing to a lot of columns. My use case right now is for mutate. I have huge datasets with EEG signals from a different electrode in each column and I'm doing signal filtering which can take a while.

But I imagine that it might be useful with summarize as well.

**Comment by markfairbanks** [comment]
Are you typically using `.by` in these cases?

**Comment by bnicenboim** [comment]
yes, but not always, sometimes I have so much data that I need to process each batch apart.
So if it would work without `.by`, it would already be useful for me.

**Comment by markfairbanks** [comment]
I'll look further into this, but I don't think this would actually slow down tidytable. Those benchmark times don't include the time it takes to make the cluster - each time I would have to make the cluster and then close it.

``` r
pacman::p_load(tidytable, parallel)

data_size <- 1000000
df <- tidytable(x = runif(data_size), y = runif(data_size), z = runif(data_size))

bench::mark(
  mutate = df %>%
    mutate.(across.(where(is.numeric), ~ .x + 1)),
  make_cluster = {
    cl <- makeCluster(2)
    stopCluster(cl)
    1
  },
  check = FALSE, iterations = 30
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 mutate           25ms   67.7ms     14.6       49MB     15.1
#> 2 make_cluster    234ms  260.7ms      3.81     350KB      0
```

**Comment by markfairbanks** [comment]
Hmm as far as I can tell this is still slower than normal `tidytable`.

``` r
pacman::p_load(tidytable, signal, parallel, rlang)

data_size <- 1000000
df <- as_tidytable(matrix(runif(30*data_size), ncol = 30))
bf <- signal::butter(3, 0.1)# 10 Hz low-pass filter

parallel_mutate <- function(col) {
  col <- ensym(col)
  df %>%
    select.(!!col) %>%
    mutate.(!!col := signal::filter(bf, !!col))
}

numeric_cols <- df %>%
  select.(where(is.numeric)) %>%
  names()

exports <- c("ensym", "select.", "mutate.", "filter", "parallel_mutate", "df", "%>%", "bf")

bench::mark(
  current = df %>%
    mutate.(across.(where(is.numeric), ~ signal::filter(bf, .x))),
  parallel = {
    cl <- makeCluster(2)
    clusterExport(cl, exports)
    out <- parLapplyLB(cl, numeric_cols, parallel_mutate)
    stopCluster(cl)
    bind_cols.(out)
  },
  check = FALSE, iterations = 30
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 current       2.87s    2.99s     0.335    3.58GB    3.13 
#> 2 parallel      3.94s    3.98s     0.251  229.94MB    0.134
```

**Comment by bnicenboim** [comment]
ok, thanks!
I will try that out with my data and code, and report back.
