### ISSUE TITLE
Edit to dt_map_dfc() to output data.table type

### ISSUE THREAD

**Issue by leungi** [markfairbanks/tidytable#5]
Reprex and suggested edit below.

``` r
packageVersion("tidydt")
#> [1] '0.2.0'

library(tidydt)
#> 
#> Attaching package: 'tidydt'
#> The following object is masked from 'package:stats':
#> 
#>     dt

not_nested <- list(col1 = c("Apple", "Orange"),
                   col2 = c("Baseball", "Football"))

purrr::map_dfc(not_nested, ~ .) %>% class()
#> [1] "tbl_df"     "tbl"        "data.frame"

# expect a data.table but got matrix
dt_map_dfc(not_nested, function(x) x) %>% class()
#> [1] "matrix"

dt_map_dfc_edit <- function (.x, .f, ...)
{
  result_list <- dt_map(.x, .f, ...)
  as_dt(as.data.frame(do.call(cbind, result_list)))
}

dt_map_dfc_edit(not_nested, function(x) x) %>% class()
#> [1] "data.table" "data.frame"

nested <- list(col1 = list(c("Apple", "Banana"),
                           c("Orange")),
               col2 = list(c("Baseball", "Soccer"),
                           c("Football")))

dt_map_dfc_edit(nested, function(x) x)
#>            col1            col2
#> 1: Apple,Banana Baseball,Soccer
#> 2:       Orange        Football
```

<sup>Created on 2020-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by markfairbanks** [comment]
Thanks for catching this. Let me look a bit more at this one. I'm trying to figure out the best way forward. I'd rather not call `as_dt(as.data.frame())` every time the function runs if possible, though it wouldn't be too big of a deal if we have to

**Comment by markfairbanks** [comment]
Updated `dt_bind_cols()` to handle the "not_nested" example. Basically `dt_bind_cols()` will apply `as.data.table()` to every element of a list.

The "nested" example you gave still doesn't work, but I think if the user gives an input that `as.data.table()` can't handle, then that will be on them to fix before calling the function.
