### ISSUE TITLE
odd fread. behaviour with colClasses

### ISSUE THREAD

**Issue by AltfunsMA** [markfairbanks/tidytable#502]
I have a very large file with a couple of ID columns containing only integers that get read in as character by both `tidytable::fread.` and `data.table::fread`.

This is already somewhat odd given I can coerce, e.g., `doc_id` to integer afterwards to perform joins, etc. and similar files generated through the same process and having similar size, etc., are read in correctly.

It gets even weirder after specifying colClasses seems to be ignored completely by `tidytable::fread.` but not `data.table::fread`.

I suspect it's some CSV-formatting issue probably in the `sent` column, which is the only one with relatively random inputs; but I'm not sure why colClasses would operate differently between tidytable and data.table.

The file is ~285 MB, available [here](https://unimelbcloud-my.sharepoint.com/:x:/g/personal/alfonso_arranz_unimelb_edu_au/EaHqX5qwn9VNqwbZbYyOj7wBXy_D7iFDSSqxT-X0r-_xPw?e=XHX8Fa).

``` r
library(tidytable)

odd_fp <-  "/data/hansard/all_hans_data/07_classified/odd_fread_behaviour.csv"

DT <- data.table::fread(odd_fp)

tidy_dt <- tidytable::fread.(odd_fp)

all.equal(DT, tidy_dt)
#> [1] "Attributes: < Component \"class\": Lengths (2, 3) differ (string compare on first 2) >"
#> [2] "Attributes: < Component \"class\": 2 string mismatches >"

map_chr.(DT, class)
#>           V1       doc_id      sent_id         sent        polar         subj 
#>  "character"  "character"  "character"  "character"    "numeric"    "numeric" 
#>       log_id    label_arg    score_arg label_offend score_offend 
#>  "character"  "character"    "numeric"  "character"    "numeric"

map_chr.(tidy_dt, class)
#>           V1       doc_id      sent_id         sent        polar         subj 
#>  "character"  "character"  "character"  "character"    "numeric"    "numeric" 
#>       log_id    label_arg    score_arg label_offend score_offend 
#>  "character"  "character"    "numeric"  "character"    "numeric"


id_only <- as.integer(tidy_dt$doc_id)


sum(is.na(id_only))
#> [1] 0



DT2 <- data.table::fread(odd_fp,
                         colClasses = list(
                           integer = c("doc_id", "sent_id"),
                           character = c("sent", "label_offend", "label_arg", "log_id"),
                           double = c("polar", "subj", "score_arg", "score_offend")
                         ))

tidy_dt2 <-  fread.(odd_fp,   colClasses = list(
    integer = c("doc_id", "sent_id"),
    character = c("sent", "label_offend", "label_arg", "log_id"),
    double = c("polar", "subj", "score_arg", "score_offend")
  ))


all.equal(DT2, tidy_dt2)
#> [1] "Datasets have different column modes. First 3: V1(character!=numeric) doc_id(character!=numeric) sent_id(character!=numeric)"

map_chr.(DT2, class)
#>           V1       doc_id      sent_id         sent        polar         subj 
#>  "character"  "character"  "character"  "character"    "numeric"    "numeric" 
#>       log_id    label_arg    score_arg label_offend score_offend 
#>  "character"  "character"    "numeric"  "character"    "numeric"

map_chr.(tidy_dt2, class)
#>           V1       doc_id      sent_id         sent        polar         subj 
#>    "integer"    "integer"    "integer"  "character"    "numeric"    "numeric" 
#>       log_id    label_arg    score_arg label_offend score_offend 
#>  "character"  "character"    "numeric"  "character"    "numeric"


id_only <- as.integer(tidy_dt2$doc_id)


sum(is.na(id_only))
#> [1] 0
```

<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by markfairbanks** [comment]
I can't seem to download the file. Does the error still occur on a smaller subset of the data? Can you send the raw csv of the smaller dataset to my gmail?

You can find my email in the `DESCRIPTION` file here: https://github.com/markfairbanks/tidytable/blob/main/DESCRIPTION

**Comment by markfairbanks** [comment]
I'll test things, but to be honest I'm a bit unsure how this could be occurring. You can see in the [code](https://github.com/markfairbanks/tidytable/blob/main/R/fread-fwrite.R) `tidytable::fread.()` is a pretty simple wrapper around `data.table::fread()`. Even `as_tidytable()` is a really simple function on the `data.table` class.

This is essentially all the code does in the background:

```r
tidytable_fread <- function(...) {
  df <- fread(...)
  class(df) <- c("tidytable", "data.table", "data.frame")
  df
}
```

**Comment by AltfunsMA** [comment]
Thanks for the quick reply! I've just tested the dataset randomly sampled down to 20% and 5% of its original size. The 20% version made data.table throw a warning  "Attempt to override column 2 <<doc_id>> of inherent type 'string' down to int32". However, the coercion afterwards happened without a glitch (no NAs created). For the 5% version, colClasses worked as expected.

Still a mystery why the full file would throw errors/warnings, but probably not worth any more time!
