### ISSUE TITLE
Allow paged printing in Rmarkdown

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#52]
Currently `tidytable` functions convert data.frame/data.table/tibble objects to a "tidytable" in the background. tidytables print more like tibbles in console, but otherwise have no features separate from a data.table.

When using Rmarkdown using `knitr::opts_chunk$set(paged.print=TRUE)` (the default) doesn't work.

@TysonStanley I've taken a couple shots at this and couldn't figure out a solution. Do you have any ideas?

**Comment by TysonStanley** [comment]
Interesting. What does the error look like?

**Comment by markfairbanks** [comment]
No error, but it prints differently. If you open an R Notebook and paste in this code you'll see that the data.table returns a "paged print" that allows you to scroll through the data, and they tidytable does a normal console print.

```r
library(tidytable)
library(data.table)

data.table(x = 1:50, y = 1:50) # Returns a paged.print

tidytable(x = 1:50, y = 1:50) # Returns a console print
```

I think I have to somehow register an S3 method for tidytable with the `knitr` or `rmarkdown` print, but I can't seem to figure out how.

Here are a couple pages I've found that seem to touch on the topic:
https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html#for-package-authors
https://community.rstudio.com/t/customizing-general-objects-formatting-output/11262

**Comment by TysonStanley** [comment]
Oh, yes. I've seen this with other output. Does the `tidytable` class have a second class (like `data.table` or `data.frame`)?

**Comment by markfairbanks** [comment]
Yep - there's 3 classes: `c("tidytable", "data.table", "data.frame")`

**Comment by TysonStanley** [comment]
That's interesting. I thought for sure `knitr` would check for that and print them with the same formatting. I'll try to read up on it over the next few days and see what I can find.

**Comment by markfairbanks** [comment]
So I don't know if this is the "correct" way, but it seems like inside `print.tidytable` there should be a way to do something like this:

```r
if ("knitr" %in% installed.packages()) {
  if (knitr::opts_chunk$get()$paged.print) {
    rmarkdown::paged_table(x)
  }
}
```

But I can't seem to get it to work. Not sure if you have any ideas on that one.

[This issue](https://github.com/rstudio/rmarkdown/issues/1085) shows that explicitly calling `print()` overrides `paged.print = TRUE`. So the "if" statement shouldn't be necessary, but I haven't been able to figure out another way

**Comment by TysonStanley** [comment]
You probably saw [this](https://github.com/rstudio/rstudio/pull/1302) but wanted to check. Have you put those arguments in the Rmarkdown yet and is it still printing wrong?

**Comment by markfairbanks** [comment]
Found a workaround! Basically - if knitr is installed and `paged.print = TRUE`, make the class of the object `c("data.table", "tidytable", "data.frame")`. If not make the class `c("tidytable", "data.table", "data.frame")`.

That makes it paged-print like a data.table, but console print like a tidytable.

```
as_tidytable <- function(x) {
  UseMethod("as_tidytable")
}

#' @export
as_tidytable.tidytable <- function(x) {
    x
}

#' @export
as_tidytable.default <- function(x) {
  if (is.data.table(x)) x <- add_class(x)
  else x <- add_class(as.data.table(x))
  x
}

add_class <- function(.data) {
  if (rlang::is_installed("knitr")) {
    if (knitr::opts_chunk$get()$paged.print %||% FALSE) {
      class(.data) <- c("data.table", "tidytable", "data.frame")
    } else {
      class(.data) <- c("tidytable", "data.table", "data.frame")
    }
  }
  .data
}
```
