### ISSUE TITLE
Add copy option to joins

### ISSUE THREAD

**Issue by erdeyl** [markfairbanks/tidytable#536]
Add copy option to joins, please. It would create a possibility for checking code.

**Comment by markfairbanks** [comment]
Can you clarify the use case? As far as I know `copy` is only useful if dealing with remote tables.

**Comment by erdeyl** [comment]
My bad. I misunderstood something. Sorry for bothering you.

**Comment by markfairbanks** [comment]
Ah gotcha, no worries 👍
