### ISSUE TITLE
Implement summarize_across.()

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#64]
@markfairbanks: not sure if I'm missing something even after checking the `man`; `dplyr::summarise_at/all/if()` are not yet implemented, ya?

Something like:
``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.6.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

iris %>% 
    summarise_if(is.numeric, mean, na.rm = TRUE)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width
#> 1     5.843333    3.057333        3.758    1.199333

iris %>% 
    summarise_at(vars(contains("Sepal")), sum, na.rm = TRUE)
#>   Sepal.Length Sepal.Width
#> 1        876.5       458.6
```

_Originally posted by @leungi in https://github.com/markfairbanks/tidytable/issues/62#issuecomment-622477712_

**Comment by markfairbanks** [comment]
@leungi These aren't implemented yet. FYI I would prefer to only make `summarize_across.()` since it can cover all 3 functions (`dplyr::summarise_at/all/if()`).

Currently tidytable has `mutate_if/at/all` only because I built those out before figuring out `mutate_across.()`.

Also - as of dplyr 1.0.0 (coming mid-May), all `if/at/all` functions will be deprecated for their own version of `across()`.

**Comment by leungi** [comment]
Thanks for prompt reply @markfairbanks.

I agree that `summarize_across.()` is the way to go.

Indeed, I saw your `mutate_across` in its early days, and wonder if `tidyverse` team took a page out of your notebook 😉

**Comment by tungmilan** [comment]
Second this feature. I use `summarize_at` and `summarize_if` quite often and would love to have them in `tidytable`. Thanks a lot @markfairbanks ! Very cool package!

**Comment by markfairbanks** [comment]
This is now implemented in the dev version of `tidytable`! Let me know if you run into any issues

**Comment by leungi** [comment]
Thanks for the quick feature add @markfairbanks 🙏

In case there are others like me, who occasionally use the `.names` args in `dplyr::across()`; make sure to revise processing workflow if switching to `tidytable::summarize_across.()`, and name resulting columns explicitly.

Also, spell `summarize` with a _z_, and not _s_ 🙂

**Comment by markfairbanks** [comment]
@leungi I added `summarise_across.()`, thanks for pointing that out. I always forget about the alternate spelling.

As for the `.names` arg, I added issues #74 & #75

**Comment by leungi** [comment]
You make me feel so bad 😝, asking for so many things.

Thanks again for all the work 🙇‍♂️

**Comment by tungmilan** [comment]
Thanks a lot @markfairbanks ! `summarize_across.()` is much slower than `dtplyr` and `data.table` solutions in the following example. What would be a faster way using `tidytable`?

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
CPU: Core i7-8750H @ 2.20GHz, 2208 Mhz, 6 Core(s), 12 Logical Processor(s)
RAM: 16 GB

package        * version     date       lib source                                  
data.table     * 1.12.9      2020-04-20 [1] local                                   
dplyr          * 0.8.99.9003 2020-05-29 [1] Github (tidyverse/dplyr@2855355)        
dtplyr         * 1.0.1.9000  2020-05-29 [1] Github (tidyverse/dtplyr@dfb22f6)
tidytable      * 0.5.0.9     2020-05-29 [1] Github (markfairbanks/tidytable@bc4b1d0)

#> Unit: milliseconds
#>              expr      min       lq     mean   median       uq      max neval
#>      dplyr_func()  16.3866  17.2444  18.8779  17.8115  19.5853  34.8279   100
#>  dplyr_acr_func() 190.3610 199.9047 207.6058 204.3143 211.3635 278.1041   100
#>     dtplyr_func()   8.1858   8.7738   9.7016   9.3106  10.1511  19.2393   100
#>  tidytable_func()  71.8009  74.0848  78.2104  76.1958  80.2190 127.3493   100
#>         dt_func()   2.7862   2.9893   3.6715   3.1622   4.4132   6.1665   100
```

``` r
library(microbenchmark)
library(data.table)
library(dtplyr)
library(dplyr)
library(tidytable)
library(ggplot2)

diamonds2 <- lazy_dt(diamonds)
dt <- setDT(copy(diamonds))

tidytable_func <- function() {
  diamonds %>% 
    summarize_across.(c(depth, table, price, carat), 
                      mean,
                      by = c(cut, color, clarity))
}

dplyr_func <- function() {
  diamonds %>% 
    group_by(cut, color, clarity) %>% 
    summarise_at(vars(depth, table, price, carat), mean)
  
}

dplyr_acr_func <- function() {
  diamonds %>% 
    group_by(cut, color, clarity) %>% 
    summarise(across(c(depth, table, price, carat), mean))
  
}

dtplyr_func <- function() {
  diamonds2 %>% 
    group_by(cut, color, clarity) %>% 
    summarise_at(vars(depth, table, price, carat), mean) %>% 
    as_tibble()
}

cols <- c("depth", "table", "price", "carat")

dt_func <- function() {
  dt[ 
    , lapply(.SD, mean)
    , by = .(cut, color, clarity)
    , .SDcols = cols]
}

microbenchmark(
  dplyr_func(),
  dplyr_acr_func(),
  dtplyr_func(),
  tidytable_func(),
  dt_func(),
  unit = 'ms',
  times = 100L
)
