### ISSUE TITLE
Check that is.data.table(DT) == TRUE

### ISSUE THREAD

**Issue by nick-youngblut** [markfairbanks/tidytable#687]
I'm developing a package that includes tidytable. I have some package data:

```
F = 'data-raw/substrate-well.tsv'
substrate_well = read.table(F, sep='\t') 
usethis::use_data(substrate_well, overwrite = TRUE)
```

The function in my package:

```
get_substrate_well = function(){
  substrate_well %>%
    mutate.(Plate = as.numeric(gsub('PM*', '', Plate)))
}
```

When I run `devtools::load_all(); get_substrate_well ()`, I get the following error:

```
Error in `:=`(Plate = as.numeric(gsub("PM*", "", Plate))) : 
Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
```

I have not idea why. I do not get the error if I use `dplyr::mutate`

**Comment by markfairbanks** [comment]
Can you see if the solution (option 1) in [this comment](https://github.com/markfairbanks/tidytable/issues/269#issuecomment-852303061) fixes the issue? I’m guessing that’s the issue.

**Comment by nick-youngblut** [comment]
Yeah, that seems to have fixed the issue. Thanks!

**Comment by markfairbanks** [comment]
Also FYI you can use `mutate()` (without the dot) in the latest version of tidytable. `mutate.()` still works too.

**Comment by nick-youngblut** [comment]
> Also FYI you can use mutate() (without the dot) in the latest version of tidytable. mutate.() still works too.

Thanks for the tip! I like to include the `.` so that it is easy to distinguish tidytable code from dplyr code.
