### ISSUE TITLE
map() pluck function not working?

### ISSUE THREAD

**Issue by docfleetwood** [markfairbanks/tidytable#693]
I was recently trying the following code...

list1 <- list(l1 = list(a = 1:5, b = 1:10, c = 1:20, d = letters[1:5]),
              l2 = list(a = 11:15, b = 11:20, c= 11:30, d = letters[3:8]),
              l3 = list(a = 21:25, b = 21:30, c = 21:40, d = letters[6:11]))

list1 %>% map_dfc("b") %>% map_dbl(mean) %>% mean()

This works with the tidyverse. But using tidytable gives me the following error...

Error in get(x, envir = env, mode = "function") : 
  object 'b' of mode 'function' was not found

I also tried it using the pluck() function - map_dfc(pluck("b")) but got the same error.

Is the pluck function not implemented in tidytable map function?

Thank you for all the hard work!

**Comment by markfairbanks** [comment]
Ah interesting! I didn't know that `pluck()` functionality worked in `map()`, so this isn't built into `tidytable::map()`. `pluck()` itself isn't implemented in `tidytable` either.

In general I've decided not to add any more `purrr` functions to `tidytable`, so for more complicated use cases (like using `pluck()`) I would just recommend using `purrr`. There are a _lot_ of `purrr` helpers, so it's a pretty slippery slope if I start adding more. In hindsight I'm not positive I would have added `map()` and just focused on `dplyr`/`tidyr` functionality, but it's been exported for so long it's going to stay.

But I'll have to think about this one. It still might be worth adding this functionality to `tidytable::map()`.

**Comment by docfleetwood** [comment]
Thank you for the information, that is good to know.

Have a great day!

**Comment by markfairbanks** [comment]
@docfleetwood - I think I'm going to keep this functionality out of tidytable per the reasoning from https://github.com/markfairbanks/tidytable/issues/693#issuecomment-1314675334.

If you run into any `dplyr`/`tidyr` functionality that is missing let me know 😄
