### ISSUE TITLE
`pivot_wider()` with `id_cols` of length 0 and `unused_fn`

### ISSUE THREAD

**Issue by Darxor** [markfairbanks/tidytable#698]
Currently specifying `character(0)` / `numeric(0)` in `id_cols` leads to behavior similar to `NULL` (the default), but also produces a warning:
``` r
df <- data.frame(
  a   = LETTERS[1:2],
  b   = LETTERS[3:4],
  val = 1:2
)

df |>
  tidytable::pivot_wider(
    id_cols = character(0),
    names_from = a,
    values_from = val
  )
#> Warning in `[.data.table`(~.df, , `:=`(., NULL)): Column '.' does not exist to
#> remove
#> # A tidytable: 2 × 3
#>   b         A     B
#>   <chr> <int> <int>
#> 1 C         1    NA
#> 2 D        NA     2
```

<sup>Created on 2022-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`{tidyr}` handles it differently. They apply function passed in the argument `unused_fn` (default is to omit columns) to all columns not mentioned in `id_cols`, `names_from`, or `values_from`, which leads to this:
``` r
df <- data.frame(
  a   = LETTERS[1:2],
  b   = LETTERS[3:4],
  val = 1:2
)

df |>
  tidyr::pivot_wider(
    id_cols = character(0),
    names_from = a,
    values_from = val
  )
#> # A tibble: 1 × 2
#>       A     B
#>   <int> <int>
#> 1     1     2
```

<sup>Created on 2022-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Another note: with `NULL` in `id_cols`, `{tidyr}` considers all columns not mentioned by `names_from`, or `values_from` as `id_cols`, which affects `id_expand` (currently also not implemented, but a thing to keep in mind for future).

I can tackle this if you want, though this may lead to a rather big change in how `pivot_wider()` is coded 😅

**Comment by Darxor** [comment]
> Interesting - I wasn't aware of this functionality.

I think my approach with tidyverse sometimes relies on a lesser-known functionality, as you can see by my issues, haha.

I will look into this, yeah! Sounds about right with that approach, I will have to think about how to identify `id_cols` and `unused_cols` correctly (order of operation concerns me a bit). I've ran some tests from `{tidyr}` that seem related to this, and currently they are not passed.

BTW, I think its also a good idea to port some tests over from tidyverse and look for missing / non-matching / broken functionality between packages.

**Comment by markfairbanks** [comment]
All set - sorry this one took so long to get to!

``` r
library(tidytable)

df <- data.frame(
  a   = LETTERS[1:2],
  b   = LETTERS[3:4],
  val = 1:2
)

df %>%
  pivot_wider(
    id_cols = character(0),
    names_from = a,
    values_from = val
  )
#> # A tidytable: 1 × 2
#>       A     B
#>   <int> <int>
#> 1     1     2
```
