### ISSUE TITLE
Add dtplyr to speed comparisons

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#72]
It would be helpful to add these for the main dplyr verbs that already currently have tests - `arrange()`, `mutate()`, `summarize()`, & `filter()`.

In case someone wants to help with this one, all tests are found in the source code of the README, and here's how `filter()` would look:

```r
filter_marks <- bench::mark(
  tidyverse = filter(test_tbl, a <= 7, c == "a"),
  # Only new line, all other parts are already written
  dtplyr = as.data.table(filter(lazy_dt(test_dt), a <= 7, c == "a")),
  tidytable = filter.(test_dt, a <= 7, c == "a"),
  data.table = test_dt[a <= 7 & c == "a"],
  check = FALSE, iterations = iters, memory = FALSE, filter_gc = FALSE, time_unit = 'ms') %>%
  mutate(expression = as.character(expression),
         function_tested = "filter")
```

For anyone new to pull requests that wants to take a shot at this - feel free to comment on this issue and I can walk you through the process.

**Comment by leungi** [comment]
@markfairbanks : I'll take this, if you may.

I do see `filter()` listed in the [speed comparison docs](https://markfairbanks.github.io/tidytable/articles/speed_comparisons.html).

Do you mean to include all verbs that you already implemented to date, but are not yet in the docs above, such as `expand()`, `separate()` etc?

**Comment by markfairbanks** [comment]
@leungi - sure that sounds great. What I'm thinking is to add [dtplyr](https://dtplyr.tidyverse.org) comparisons for 4 core `dplyr` verbs - `arrange()`, `mutate()`, `summarize()`, & `filter()`.

In my example above, the only new test is the `dtplyr` line. So in the end this will only add a few lines of code to the existing docs.

All current speed tests are found [in this file](https://github.com/markfairbanks/tidytable/blob/master/vignettes/speed_comparisons.Rmd).

**Comment by leungi** [comment]
Gotcha; I do see `dtplyr` missing as a column in the speed comparison section.

Will do a PR on completion.
