### ISSUE TITLE
Add .names arg to summarize_across.()

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#74]

**Comment by markfairbanks** [comment]
@leungi 

FYI - `mutate_across.()` & `summarize_across.()` now have a `.names` arg in the development version of `tidytable`. If you run into any issues let me know. 

The column naming conventions also now match the `dplyr` implementation. 

The new column naming is a breaking change for:
* `mutate_across.()`: Only when passing an unnamed list to `.fns`
* `summarize_across.()`: All uses

Here's an example of how `summarize_across.()` has changed:

```r
pacman::p_load(tidytable)

test_df <- data.table(a = 1:3, b = 4:6, z = c("a", "a", "b"))

# Old version
test_df %>%
  summarize_across.(c(a, b), list(mean, max))
#>    z fn1_a fn1_b fn2_a fn2_b
#> 1: a   2     5     3     6

# New version: Auto-created names now match dplyr
test_df %>%
  summarize_across.(c(a, b), list(mean, max))
#>    a_1 b_1 a_2 b_2
#> 1:   2   5   3   6

# Using .names
test_df %>%
  summarize_across.(c(a, b), list(avg = mean, max = max), .names = "{col}_{fn}_test")
#>    a_avg_test b_avg_test a_max_test b_max_test
#> 1:          2          5          3          6
```

**Comment by leungi** [comment]
@markfairbanks : appreciate your work as always, and thanks for always keeping in mind when implementing these changes!
