### ISSUE TITLE
exposing list_flatten

### ISSUE THREAD

**Issue by bnicenboim** [markfairbanks/tidytable#797]
Could you expose `list_flatten`? It would be nice to avoid a dependency to purrr.

**Comment by markfairbanks** [comment]
Feel free to just copy the code from my repo and use `list_flatten()` where you need it. I've decided I'm not going to export any more `purrr` functions from `tidytable`. There are just way too many for me to recreate all of them. In hindsight I probably shouldn't have exported `map()` functions either but they're going to stay at this point.
