### ISSUE TITLE
group_indices()

### ISSUE THREAD

**Issue by erdeyl** [markfairbanks/tidytable#829]
Hi Mark,

Tidytable is fantastic. Do you plan to include dplyr's group_indices()?

Cheers,
Laszlo

**Comment by markfairbanks** [comment]
Sure I can add it

**Comment by markfairbanks** [comment]
FYI - in the meantime you can use `cur_group_id()`

``` r
library(tidytable)

df <- tidytable(x = 1:3, y = c("a", "b", "a"))

df %>%
  group_by(y) %>%
  mutate(group_id = cur_group_id()) %>%
  pull(group_id)
#> [1] 1 2 1
```

**Comment by markfairbanks** [comment]
Actually as I look into this more, it looks like `group_indices()` has been deprecated in favor of `cur_group_id()` as of [dplyr 1.0.0](https://dplyr.tidyverse.org/news/index.html?q=group_indices#deprecated-1-0-0). Because of that I'm going to skip adding this to `tidytable`.

>The use of zero-arg [group_indices()](https://dplyr.tidyverse.org/reference/group_data.html) to retrieve the group id for the “current” group is deprecated; instead use [cur_group_id()](https://dplyr.tidyverse.org/reference/context.html).

**Comment by erdeyl** [comment]
Thank you very much!
