### ISSUE TITLE
slice.() inconsistent with dplyr variant

### ISSUE THREAD

**Issue by mattsams89** [markfairbanks/tidytable#99]
Not sure if this was maybe introduced in #85, but I had a coworker mention one of our dashboard plots was returning all dates in a selected range instead of only the rows he was selecting (some DT proxy magic). I investigated, and it seems like the issue is coming from this part of the slice.() function:

```r
tidytable:::eval_quo(
    .df[, .SD[1:.N %between% c(min(!!rows), max(!!rows))], by = .by]
  )
```

For comparison:
```r
library(dplyr)
library(tidytable)

test_df <- tidytable(name = rep(c("bill", "bob", "dan", "cindy"), each = 10),
                     value = rep(1:10, times = 4))

# dplyr
test_df %>% 
  group_by(name) %>% 
  slice(c(1, 3, 10))

# tidytable
test_df %>% 
  slice.(c(1, 3, 10),
         .by = name)
```

Converting the `%between%...` to `%in% !!rows` seems to work, although I haven't tested it enough to know if there are any unintended consequences.

**Comment by markfairbanks** [comment]
Ah yep, sorry about that - this was definitely an issue created by #85 . For some reason I hadn't though of passing a vector with irregular gaps like `c(1,3,10)`. The `%in%` solution is definitely cleaner anyway, I'll update asap.

**Comment by markfairbanks** [comment]
All set. There's a slight difference in result as `dplyr` rearranges the grouping columns by default, and `tidytable` uses `by` instead of `keyby` with `data.table`.

``` r
library(dplyr, warn.conflicts = FALSE)
library(tidytable, warn.conflicts = FALSE)

test_df <- tidytable(name = rep(c("bill", "bob", "dan", "cindy"), each = 10),
                     value = rep(1:10, times = 4))

# dplyr
test_df %>% 
  group_by(name) %>% 
  slice(c(1, 3, 10))
#> # A tibble: 12 x 2
#> # Groups:   name [4]
#>    name  value
#>    <chr> <int>
#>  1 bill      1
#>  2 bill      3
#>  3 bill     10
#>  4 bob       1
#>  5 bob       3
#>  6 bob      10
#>  7 cindy     1
#>  8 cindy     3
#>  9 cindy    10
#> 10 dan       1
#> 11 dan       3
#> 12 dan      10

# tidytable
test_df %>% 
  slice.(c(1, 3, 10),
         .by = name)
#>      name value
#>  1:  bill     1
#>  2:  bill     3
#>  3:  bill    10
#>  4:   bob     1
#>  5:   bob     3
#>  6:   bob    10
#>  7:   dan     1
#>  8:   dan     3
#>  9:   dan    10
#> 10: cindy     1
#> 11: cindy     3
#> 12: cindy    10
```
